// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

typedef enum {
  CommonEventProtocolRequestCCreateAccountViaFacebookEvent = 1,
  CommonEventProtocolRequestCCreateAccountViaEmailEvent = 2,
  CommonEventProtocolRequestCCreateAccountViaNoCredentialsEvent = 3,
  CommonEventProtocolRequestCLoginEvent = 4,
  CommonEventProtocolRequestCInAppPurchaseEvent = 5,
  CommonEventProtocolRequestCLogoutEvent = 51,
} CommonEventProtocolRequest;

BOOL CommonEventProtocolRequestIsValidValue(CommonEventProtocolRequest value);

typedef enum {
  CommonEventProtocolResponseSCreateAccountViaFacebookEvent = 1,
  CommonEventProtocolResponseSCreateAccountViaEmailEvent = 2,
  CommonEventProtocolResponseSCreateAccountViaNoCredentialsEvent = 3,
  CommonEventProtocolResponseSLoginEvent = 4,
  CommonEventProtocolResponseSInAppPurchaseEvent = 5,
  CommonEventProtocolResponseSForceLogoutEvent = 50,
} CommonEventProtocolResponse;

BOOL CommonEventProtocolResponseIsValidValue(CommonEventProtocolResponse value);


@interface CommonEventProtocolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

