// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "TriviaRoundFormat.pb.h"
#import "User.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicRoundProto;
@class BasicRoundProto_Builder;
@class BasicRoundResultsProto;
@class BasicRoundResultsProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteRoundResultsProto;
@class CompleteRoundResultsProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class CompletedRoundRequestProto;
@class CompletedRoundRequestProto_Builder;
@class CompletedRoundResponseProto;
@class CompletedRoundResponseProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionAnsweredProto;
@class QuestionAnsweredProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
@class UserCurrencyProto;
@class UserCurrencyProto_Builder;
typedef enum {
  CompletedRoundResponseProto_CompletedRoundStatusSuccess = 1,
  CompletedRoundResponseProto_CompletedRoundStatusFailGameDoesNotExist = 2,
  CompletedRoundResponseProto_CompletedRoundStatusFailGameAlreadyCompleted = 3,
  CompletedRoundResponseProto_CompletedRoundStatusFailOther = 4,
} CompletedRoundResponseProto_CompletedRoundStatus;

BOOL CompletedRoundResponseProto_CompletedRoundStatusIsValidValue(CompletedRoundResponseProto_CompletedRoundStatus value);


@interface CompletedRoundEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CompletedRoundRequestProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasSender_:1;
  BOOL hasResults_:1;
  NSString* gameId;
  BasicUserProto* sender;
  CompleteRoundResultsProto* results;
}
- (BOOL) hasSender;
- (BOOL) hasGameId;
- (BOOL) hasResults;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly, retain) NSString* gameId;
@property (readonly, retain) CompleteRoundResultsProto* results;

+ (CompletedRoundRequestProto*) defaultInstance;
- (CompletedRoundRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CompletedRoundRequestProto_Builder*) builder;
+ (CompletedRoundRequestProto_Builder*) builder;
+ (CompletedRoundRequestProto_Builder*) builderWithPrototype:(CompletedRoundRequestProto*) prototype;

+ (CompletedRoundRequestProto*) parseFromData:(NSData*) data;
+ (CompletedRoundRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (CompletedRoundRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CompletedRoundRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CompletedRoundRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  CompletedRoundRequestProto* result;
}

- (CompletedRoundRequestProto*) defaultInstance;

- (CompletedRoundRequestProto_Builder*) clear;
- (CompletedRoundRequestProto_Builder*) clone;

- (CompletedRoundRequestProto*) build;
- (CompletedRoundRequestProto*) buildPartial;

- (CompletedRoundRequestProto_Builder*) mergeFrom:(CompletedRoundRequestProto*) other;
- (CompletedRoundRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CompletedRoundRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (CompletedRoundRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (CompletedRoundRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (CompletedRoundRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (CompletedRoundRequestProto_Builder*) clearSender;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (CompletedRoundRequestProto_Builder*) setGameId:(NSString*) value;
- (CompletedRoundRequestProto_Builder*) clearGameId;

- (BOOL) hasResults;
- (CompleteRoundResultsProto*) results;
- (CompletedRoundRequestProto_Builder*) setResults:(CompleteRoundResultsProto*) value;
- (CompletedRoundRequestProto_Builder*) setResultsBuilder:(CompleteRoundResultsProto_Builder*) builderForValue;
- (CompletedRoundRequestProto_Builder*) mergeResults:(CompleteRoundResultsProto*) value;
- (CompletedRoundRequestProto_Builder*) clearResults;
@end

@interface CompletedRoundResponseProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasRecipient_:1;
  BOOL hasResults_:1;
  BOOL hasStatus_:1;
  NSString* gameId;
  BasicUserProto* recipient;
  BasicRoundResultsProto* results;
  CompletedRoundResponseProto_CompletedRoundStatus status;
}
- (BOOL) hasRecipient;
- (BOOL) hasGameId;
- (BOOL) hasResults;
- (BOOL) hasStatus;
@property (readonly, retain) BasicUserProto* recipient;
@property (readonly, retain) NSString* gameId;
@property (readonly, retain) BasicRoundResultsProto* results;
@property (readonly) CompletedRoundResponseProto_CompletedRoundStatus status;

+ (CompletedRoundResponseProto*) defaultInstance;
- (CompletedRoundResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CompletedRoundResponseProto_Builder*) builder;
+ (CompletedRoundResponseProto_Builder*) builder;
+ (CompletedRoundResponseProto_Builder*) builderWithPrototype:(CompletedRoundResponseProto*) prototype;

+ (CompletedRoundResponseProto*) parseFromData:(NSData*) data;
+ (CompletedRoundResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (CompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CompletedRoundResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  CompletedRoundResponseProto* result;
}

- (CompletedRoundResponseProto*) defaultInstance;

- (CompletedRoundResponseProto_Builder*) clear;
- (CompletedRoundResponseProto_Builder*) clone;

- (CompletedRoundResponseProto*) build;
- (CompletedRoundResponseProto*) buildPartial;

- (CompletedRoundResponseProto_Builder*) mergeFrom:(CompletedRoundResponseProto*) other;
- (CompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (CompletedRoundResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (CompletedRoundResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (CompletedRoundResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (CompletedRoundResponseProto_Builder*) clearRecipient;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (CompletedRoundResponseProto_Builder*) setGameId:(NSString*) value;
- (CompletedRoundResponseProto_Builder*) clearGameId;

- (BOOL) hasResults;
- (BasicRoundResultsProto*) results;
- (CompletedRoundResponseProto_Builder*) setResults:(BasicRoundResultsProto*) value;
- (CompletedRoundResponseProto_Builder*) setResultsBuilder:(BasicRoundResultsProto_Builder*) builderForValue;
- (CompletedRoundResponseProto_Builder*) mergeResults:(BasicRoundResultsProto*) value;
- (CompletedRoundResponseProto_Builder*) clearResults;

- (BOOL) hasStatus;
- (CompletedRoundResponseProto_CompletedRoundStatus) status;
- (CompletedRoundResponseProto_Builder*) setStatus:(CompletedRoundResponseProto_CompletedRoundStatus) value;
- (CompletedRoundResponseProto_Builder*) clearStatus;
@end

