// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "User.pb.h"
#import "TriviaRoundFormat.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicRoundProto;
@class BasicRoundProto_Builder;
@class BasicRoundResultsProto;
@class BasicRoundResultsProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteRoundResultsProto;
@class CompleteRoundResultsProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class CompletedRoundRequestProto;
@class CompletedRoundRequestProto_Builder;
@class CompletedRoundResponseProto;
@class CompletedRoundResponseProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class OtherUserCompletedRoundResponseProto;
@class OtherUserCompletedRoundResponseProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
typedef enum {
  CompletedRoundResponseProto_CompletedRoundResponseStatusSuccess = 1,
  CompletedRoundResponseProto_CompletedRoundResponseStatusFailGameDoesNotExist = 2,
  CompletedRoundResponseProto_CompletedRoundResponseStatusFailGameAlreadyCompleted = 3,
  CompletedRoundResponseProto_CompletedRoundResponseStatusFailIncorrectScore = 4,
  CompletedRoundResponseProto_CompletedRoundResponseStatusFailOther = 5,
  CompletedRoundResponseProto_CompletedRoundResponseStatusFailClientTooApartFromServerTime = 6,
} CompletedRoundResponseProto_CompletedRoundResponseStatus;

BOOL CompletedRoundResponseProto_CompletedRoundResponseStatusIsValidValue(CompletedRoundResponseProto_CompletedRoundResponseStatus value);


@interface CompletedRoundEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CompletedRoundRequestProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasSender_:1;
  BOOL hasResults_:1;
  NSString* gameId;
  BasicUserProto* sender;
  CompleteRoundResultsProto* results;
}
- (BOOL) hasSender;
- (BOOL) hasGameId;
- (BOOL) hasResults;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly, retain) NSString* gameId;
@property (readonly, retain) CompleteRoundResultsProto* results;

+ (CompletedRoundRequestProto*) defaultInstance;
- (CompletedRoundRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CompletedRoundRequestProto_Builder*) builder;
+ (CompletedRoundRequestProto_Builder*) builder;
+ (CompletedRoundRequestProto_Builder*) builderWithPrototype:(CompletedRoundRequestProto*) prototype;

+ (CompletedRoundRequestProto*) parseFromData:(NSData*) data;
+ (CompletedRoundRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (CompletedRoundRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CompletedRoundRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CompletedRoundRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  CompletedRoundRequestProto* result;
}

- (CompletedRoundRequestProto*) defaultInstance;

- (CompletedRoundRequestProto_Builder*) clear;
- (CompletedRoundRequestProto_Builder*) clone;

- (CompletedRoundRequestProto*) build;
- (CompletedRoundRequestProto*) buildPartial;

- (CompletedRoundRequestProto_Builder*) mergeFrom:(CompletedRoundRequestProto*) other;
- (CompletedRoundRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CompletedRoundRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (CompletedRoundRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (CompletedRoundRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (CompletedRoundRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (CompletedRoundRequestProto_Builder*) clearSender;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (CompletedRoundRequestProto_Builder*) setGameId:(NSString*) value;
- (CompletedRoundRequestProto_Builder*) clearGameId;

- (BOOL) hasResults;
- (CompleteRoundResultsProto*) results;
- (CompletedRoundRequestProto_Builder*) setResults:(CompleteRoundResultsProto*) value;
- (CompletedRoundRequestProto_Builder*) setResultsBuilder:(CompleteRoundResultsProto_Builder*) builderForValue;
- (CompletedRoundRequestProto_Builder*) mergeResults:(CompleteRoundResultsProto*) value;
- (CompletedRoundRequestProto_Builder*) clearResults;
@end

@interface CompletedRoundResponseProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasRecipient_:1;
  BOOL hasResults_:1;
  BOOL hasStatus_:1;
  NSString* gameId;
  BasicUserProto* recipient;
  BasicRoundResultsProto* results;
  CompletedRoundResponseProto_CompletedRoundResponseStatus status;
}
- (BOOL) hasRecipient;
- (BOOL) hasGameId;
- (BOOL) hasResults;
- (BOOL) hasStatus;
@property (readonly, retain) BasicUserProto* recipient;
@property (readonly, retain) NSString* gameId;
@property (readonly, retain) BasicRoundResultsProto* results;
@property (readonly) CompletedRoundResponseProto_CompletedRoundResponseStatus status;

+ (CompletedRoundResponseProto*) defaultInstance;
- (CompletedRoundResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CompletedRoundResponseProto_Builder*) builder;
+ (CompletedRoundResponseProto_Builder*) builder;
+ (CompletedRoundResponseProto_Builder*) builderWithPrototype:(CompletedRoundResponseProto*) prototype;

+ (CompletedRoundResponseProto*) parseFromData:(NSData*) data;
+ (CompletedRoundResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (CompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CompletedRoundResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  CompletedRoundResponseProto* result;
}

- (CompletedRoundResponseProto*) defaultInstance;

- (CompletedRoundResponseProto_Builder*) clear;
- (CompletedRoundResponseProto_Builder*) clone;

- (CompletedRoundResponseProto*) build;
- (CompletedRoundResponseProto*) buildPartial;

- (CompletedRoundResponseProto_Builder*) mergeFrom:(CompletedRoundResponseProto*) other;
- (CompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (CompletedRoundResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (CompletedRoundResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (CompletedRoundResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (CompletedRoundResponseProto_Builder*) clearRecipient;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (CompletedRoundResponseProto_Builder*) setGameId:(NSString*) value;
- (CompletedRoundResponseProto_Builder*) clearGameId;

- (BOOL) hasResults;
- (BasicRoundResultsProto*) results;
- (CompletedRoundResponseProto_Builder*) setResults:(BasicRoundResultsProto*) value;
- (CompletedRoundResponseProto_Builder*) setResultsBuilder:(BasicRoundResultsProto_Builder*) builderForValue;
- (CompletedRoundResponseProto_Builder*) mergeResults:(BasicRoundResultsProto*) value;
- (CompletedRoundResponseProto_Builder*) clearResults;

- (BOOL) hasStatus;
- (CompletedRoundResponseProto_CompletedRoundResponseStatus) status;
- (CompletedRoundResponseProto_Builder*) setStatus:(CompletedRoundResponseProto_CompletedRoundResponseStatus) value;
- (CompletedRoundResponseProto_Builder*) clearStatus;
@end

@interface OtherUserCompletedRoundResponseProto : PBGeneratedMessage {
@private
  BOOL hasRecipient_:1;
  BOOL hasUserWhoCompletedRound_:1;
  BOOL hasRoundUserCompletedBasic_:1;
  BOOL hasRoundUserCompleted_:1;
  BasicUserProto* recipient;
  BasicUserProto* userWhoCompletedRound;
  BasicRoundResultsProto* roundUserCompletedBasic;
  CompleteRoundResultsProto* roundUserCompleted;
}
- (BOOL) hasRecipient;
- (BOOL) hasUserWhoCompletedRound;
- (BOOL) hasRoundUserCompletedBasic;
- (BOOL) hasRoundUserCompleted;
@property (readonly, retain) BasicUserProto* recipient;
@property (readonly, retain) BasicUserProto* userWhoCompletedRound;
@property (readonly, retain) BasicRoundResultsProto* roundUserCompletedBasic;
@property (readonly, retain) CompleteRoundResultsProto* roundUserCompleted;

+ (OtherUserCompletedRoundResponseProto*) defaultInstance;
- (OtherUserCompletedRoundResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OtherUserCompletedRoundResponseProto_Builder*) builder;
+ (OtherUserCompletedRoundResponseProto_Builder*) builder;
+ (OtherUserCompletedRoundResponseProto_Builder*) builderWithPrototype:(OtherUserCompletedRoundResponseProto*) prototype;

+ (OtherUserCompletedRoundResponseProto*) parseFromData:(NSData*) data;
+ (OtherUserCompletedRoundResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OtherUserCompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (OtherUserCompletedRoundResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OtherUserCompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OtherUserCompletedRoundResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OtherUserCompletedRoundResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  OtherUserCompletedRoundResponseProto* result;
}

- (OtherUserCompletedRoundResponseProto*) defaultInstance;

- (OtherUserCompletedRoundResponseProto_Builder*) clear;
- (OtherUserCompletedRoundResponseProto_Builder*) clone;

- (OtherUserCompletedRoundResponseProto*) build;
- (OtherUserCompletedRoundResponseProto*) buildPartial;

- (OtherUserCompletedRoundResponseProto_Builder*) mergeFrom:(OtherUserCompletedRoundResponseProto*) other;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (OtherUserCompletedRoundResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) clearRecipient;

- (BOOL) hasUserWhoCompletedRound;
- (BasicUserProto*) userWhoCompletedRound;
- (OtherUserCompletedRoundResponseProto_Builder*) setUserWhoCompletedRound:(BasicUserProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) setUserWhoCompletedRoundBuilder:(BasicUserProto_Builder*) builderForValue;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeUserWhoCompletedRound:(BasicUserProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) clearUserWhoCompletedRound;

- (BOOL) hasRoundUserCompletedBasic;
- (BasicRoundResultsProto*) roundUserCompletedBasic;
- (OtherUserCompletedRoundResponseProto_Builder*) setRoundUserCompletedBasic:(BasicRoundResultsProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) setRoundUserCompletedBasicBuilder:(BasicRoundResultsProto_Builder*) builderForValue;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeRoundUserCompletedBasic:(BasicRoundResultsProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) clearRoundUserCompletedBasic;

- (BOOL) hasRoundUserCompleted;
- (CompleteRoundResultsProto*) roundUserCompleted;
- (OtherUserCompletedRoundResponseProto_Builder*) setRoundUserCompleted:(CompleteRoundResultsProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) setRoundUserCompletedBuilder:(CompleteRoundResultsProto_Builder*) builderForValue;
- (OtherUserCompletedRoundResponseProto_Builder*) mergeRoundUserCompleted:(CompleteRoundResultsProto*) value;
- (OtherUserCompletedRoundResponseProto_Builder*) clearRoundUserCompleted;
@end

