// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "CreateAccountEvent.pb.h"

@implementation CreateAccountEventRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [CreateAccountEventRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface CreateAccountViaFacebookRequestProto ()
@property (retain) NSString* facebookId;
@property (retain) NSString* nameFriendsSee;
@property (retain) NSString* email;
@property (retain) NSString* udid;
@property (retain) NSString* deviceId;
@end

@implementation CreateAccountViaFacebookRequestProto

- (BOOL) hasFacebookId {
  return !!hasFacebookId_;
}
- (void) setHasFacebookId:(BOOL) value {
  hasFacebookId_ = !!value;
}
@synthesize facebookId;
- (BOOL) hasNameFriendsSee {
  return !!hasNameFriendsSee_;
}
- (void) setHasNameFriendsSee:(BOOL) value {
  hasNameFriendsSee_ = !!value;
}
@synthesize nameFriendsSee;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasUdid {
  return !!hasUdid_;
}
- (void) setHasUdid:(BOOL) value {
  hasUdid_ = !!value;
}
@synthesize udid;
- (BOOL) hasDeviceId {
  return !!hasDeviceId_;
}
- (void) setHasDeviceId:(BOOL) value {
  hasDeviceId_ = !!value;
}
@synthesize deviceId;
- (void) dealloc {
  self.facebookId = nil;
  self.nameFriendsSee = nil;
  self.email = nil;
  self.udid = nil;
  self.deviceId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.facebookId = @"";
    self.nameFriendsSee = @"";
    self.email = @"";
    self.udid = @"";
    self.deviceId = @"";
  }
  return self;
}
static CreateAccountViaFacebookRequestProto* defaultCreateAccountViaFacebookRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [CreateAccountViaFacebookRequestProto class]) {
    defaultCreateAccountViaFacebookRequestProtoInstance = [[CreateAccountViaFacebookRequestProto alloc] init];
  }
}
+ (CreateAccountViaFacebookRequestProto*) defaultInstance {
  return defaultCreateAccountViaFacebookRequestProtoInstance;
}
- (CreateAccountViaFacebookRequestProto*) defaultInstance {
  return defaultCreateAccountViaFacebookRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasFacebookId) {
    [output writeString:1 value:self.facebookId];
  }
  if (self.hasNameFriendsSee) {
    [output writeString:2 value:self.nameFriendsSee];
  }
  if (self.hasEmail) {
    [output writeString:3 value:self.email];
  }
  if (self.hasUdid) {
    [output writeString:4 value:self.udid];
  }
  if (self.hasDeviceId) {
    [output writeString:5 value:self.deviceId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasFacebookId) {
    size += computeStringSize(1, self.facebookId);
  }
  if (self.hasNameFriendsSee) {
    size += computeStringSize(2, self.nameFriendsSee);
  }
  if (self.hasEmail) {
    size += computeStringSize(3, self.email);
  }
  if (self.hasUdid) {
    size += computeStringSize(4, self.udid);
  }
  if (self.hasDeviceId) {
    size += computeStringSize(5, self.deviceId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CreateAccountViaFacebookRequestProto*) parseFromData:(NSData*) data {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromData:data] build];
}
+ (CreateAccountViaFacebookRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaFacebookRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromInputStream:input] build];
}
+ (CreateAccountViaFacebookRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaFacebookRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (CreateAccountViaFacebookRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaFacebookRequestProto*)[[[CreateAccountViaFacebookRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaFacebookRequestProto_Builder*) builder {
  return [[[CreateAccountViaFacebookRequestProto_Builder alloc] init] autorelease];
}
+ (CreateAccountViaFacebookRequestProto_Builder*) builderWithPrototype:(CreateAccountViaFacebookRequestProto*) prototype {
  return [[CreateAccountViaFacebookRequestProto builder] mergeFrom:prototype];
}
- (CreateAccountViaFacebookRequestProto_Builder*) builder {
  return [CreateAccountViaFacebookRequestProto builder];
}
@end

@interface CreateAccountViaFacebookRequestProto_Builder()
@property (retain) CreateAccountViaFacebookRequestProto* result;
@end

@implementation CreateAccountViaFacebookRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CreateAccountViaFacebookRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clear {
  self.result = [[[CreateAccountViaFacebookRequestProto alloc] init] autorelease];
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clone {
  return [CreateAccountViaFacebookRequestProto builderWithPrototype:result];
}
- (CreateAccountViaFacebookRequestProto*) defaultInstance {
  return [CreateAccountViaFacebookRequestProto defaultInstance];
}
- (CreateAccountViaFacebookRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CreateAccountViaFacebookRequestProto*) buildPartial {
  CreateAccountViaFacebookRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CreateAccountViaFacebookRequestProto_Builder*) mergeFrom:(CreateAccountViaFacebookRequestProto*) other {
  if (other == [CreateAccountViaFacebookRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasFacebookId) {
    [self setFacebookId:other.facebookId];
  }
  if (other.hasNameFriendsSee) {
    [self setNameFriendsSee:other.nameFriendsSee];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasUdid) {
    [self setUdid:other.udid];
  }
  if (other.hasDeviceId) {
    [self setDeviceId:other.deviceId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CreateAccountViaFacebookRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setFacebookId:[input readString]];
        break;
      }
      case 18: {
        [self setNameFriendsSee:[input readString]];
        break;
      }
      case 26: {
        [self setEmail:[input readString]];
        break;
      }
      case 34: {
        [self setUdid:[input readString]];
        break;
      }
      case 42: {
        [self setDeviceId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasFacebookId {
  return result.hasFacebookId;
}
- (NSString*) facebookId {
  return result.facebookId;
}
- (CreateAccountViaFacebookRequestProto_Builder*) setFacebookId:(NSString*) value {
  result.hasFacebookId = YES;
  result.facebookId = value;
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clearFacebookId {
  result.hasFacebookId = NO;
  result.facebookId = @"";
  return self;
}
- (BOOL) hasNameFriendsSee {
  return result.hasNameFriendsSee;
}
- (NSString*) nameFriendsSee {
  return result.nameFriendsSee;
}
- (CreateAccountViaFacebookRequestProto_Builder*) setNameFriendsSee:(NSString*) value {
  result.hasNameFriendsSee = YES;
  result.nameFriendsSee = value;
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clearNameFriendsSee {
  result.hasNameFriendsSee = NO;
  result.nameFriendsSee = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (CreateAccountViaFacebookRequestProto_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasUdid {
  return result.hasUdid;
}
- (NSString*) udid {
  return result.udid;
}
- (CreateAccountViaFacebookRequestProto_Builder*) setUdid:(NSString*) value {
  result.hasUdid = YES;
  result.udid = value;
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clearUdid {
  result.hasUdid = NO;
  result.udid = @"";
  return self;
}
- (BOOL) hasDeviceId {
  return result.hasDeviceId;
}
- (NSString*) deviceId {
  return result.deviceId;
}
- (CreateAccountViaFacebookRequestProto_Builder*) setDeviceId:(NSString*) value {
  result.hasDeviceId = YES;
  result.deviceId = value;
  return self;
}
- (CreateAccountViaFacebookRequestProto_Builder*) clearDeviceId {
  result.hasDeviceId = NO;
  result.deviceId = @"";
  return self;
}
@end

@interface CreateAccountViaEmailRequestProto ()
@property (retain) NSString* nameStrangersSee;
@property (retain) NSString* email;
@property (retain) NSString* password;
@property (retain) NSString* udid;
@property (retain) NSString* deviceId;
@end

@implementation CreateAccountViaEmailRequestProto

- (BOOL) hasNameStrangersSee {
  return !!hasNameStrangersSee_;
}
- (void) setHasNameStrangersSee:(BOOL) value {
  hasNameStrangersSee_ = !!value;
}
@synthesize nameStrangersSee;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasUdid {
  return !!hasUdid_;
}
- (void) setHasUdid:(BOOL) value {
  hasUdid_ = !!value;
}
@synthesize udid;
- (BOOL) hasDeviceId {
  return !!hasDeviceId_;
}
- (void) setHasDeviceId:(BOOL) value {
  hasDeviceId_ = !!value;
}
@synthesize deviceId;
- (void) dealloc {
  self.nameStrangersSee = nil;
  self.email = nil;
  self.password = nil;
  self.udid = nil;
  self.deviceId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.nameStrangersSee = @"";
    self.email = @"";
    self.password = @"";
    self.udid = @"";
    self.deviceId = @"";
  }
  return self;
}
static CreateAccountViaEmailRequestProto* defaultCreateAccountViaEmailRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [CreateAccountViaEmailRequestProto class]) {
    defaultCreateAccountViaEmailRequestProtoInstance = [[CreateAccountViaEmailRequestProto alloc] init];
  }
}
+ (CreateAccountViaEmailRequestProto*) defaultInstance {
  return defaultCreateAccountViaEmailRequestProtoInstance;
}
- (CreateAccountViaEmailRequestProto*) defaultInstance {
  return defaultCreateAccountViaEmailRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNameStrangersSee) {
    [output writeString:1 value:self.nameStrangersSee];
  }
  if (self.hasEmail) {
    [output writeString:2 value:self.email];
  }
  if (self.hasPassword) {
    [output writeString:3 value:self.password];
  }
  if (self.hasUdid) {
    [output writeString:4 value:self.udid];
  }
  if (self.hasDeviceId) {
    [output writeString:5 value:self.deviceId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNameStrangersSee) {
    size += computeStringSize(1, self.nameStrangersSee);
  }
  if (self.hasEmail) {
    size += computeStringSize(2, self.email);
  }
  if (self.hasPassword) {
    size += computeStringSize(3, self.password);
  }
  if (self.hasUdid) {
    size += computeStringSize(4, self.udid);
  }
  if (self.hasDeviceId) {
    size += computeStringSize(5, self.deviceId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CreateAccountViaEmailRequestProto*) parseFromData:(NSData*) data {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromData:data] build];
}
+ (CreateAccountViaEmailRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaEmailRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromInputStream:input] build];
}
+ (CreateAccountViaEmailRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaEmailRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (CreateAccountViaEmailRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaEmailRequestProto*)[[[CreateAccountViaEmailRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaEmailRequestProto_Builder*) builder {
  return [[[CreateAccountViaEmailRequestProto_Builder alloc] init] autorelease];
}
+ (CreateAccountViaEmailRequestProto_Builder*) builderWithPrototype:(CreateAccountViaEmailRequestProto*) prototype {
  return [[CreateAccountViaEmailRequestProto builder] mergeFrom:prototype];
}
- (CreateAccountViaEmailRequestProto_Builder*) builder {
  return [CreateAccountViaEmailRequestProto builder];
}
@end

@interface CreateAccountViaEmailRequestProto_Builder()
@property (retain) CreateAccountViaEmailRequestProto* result;
@end

@implementation CreateAccountViaEmailRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CreateAccountViaEmailRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CreateAccountViaEmailRequestProto_Builder*) clear {
  self.result = [[[CreateAccountViaEmailRequestProto alloc] init] autorelease];
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clone {
  return [CreateAccountViaEmailRequestProto builderWithPrototype:result];
}
- (CreateAccountViaEmailRequestProto*) defaultInstance {
  return [CreateAccountViaEmailRequestProto defaultInstance];
}
- (CreateAccountViaEmailRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CreateAccountViaEmailRequestProto*) buildPartial {
  CreateAccountViaEmailRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CreateAccountViaEmailRequestProto_Builder*) mergeFrom:(CreateAccountViaEmailRequestProto*) other {
  if (other == [CreateAccountViaEmailRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasNameStrangersSee) {
    [self setNameStrangersSee:other.nameStrangersSee];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasUdid) {
    [self setUdid:other.udid];
  }
  if (other.hasDeviceId) {
    [self setDeviceId:other.deviceId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CreateAccountViaEmailRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setNameStrangersSee:[input readString]];
        break;
      }
      case 18: {
        [self setEmail:[input readString]];
        break;
      }
      case 26: {
        [self setPassword:[input readString]];
        break;
      }
      case 34: {
        [self setUdid:[input readString]];
        break;
      }
      case 42: {
        [self setDeviceId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasNameStrangersSee {
  return result.hasNameStrangersSee;
}
- (NSString*) nameStrangersSee {
  return result.nameStrangersSee;
}
- (CreateAccountViaEmailRequestProto_Builder*) setNameStrangersSee:(NSString*) value {
  result.hasNameStrangersSee = YES;
  result.nameStrangersSee = value;
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clearNameStrangersSee {
  result.hasNameStrangersSee = NO;
  result.nameStrangersSee = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (CreateAccountViaEmailRequestProto_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (CreateAccountViaEmailRequestProto_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasUdid {
  return result.hasUdid;
}
- (NSString*) udid {
  return result.udid;
}
- (CreateAccountViaEmailRequestProto_Builder*) setUdid:(NSString*) value {
  result.hasUdid = YES;
  result.udid = value;
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clearUdid {
  result.hasUdid = NO;
  result.udid = @"";
  return self;
}
- (BOOL) hasDeviceId {
  return result.hasDeviceId;
}
- (NSString*) deviceId {
  return result.deviceId;
}
- (CreateAccountViaEmailRequestProto_Builder*) setDeviceId:(NSString*) value {
  result.hasDeviceId = YES;
  result.deviceId = value;
  return self;
}
- (CreateAccountViaEmailRequestProto_Builder*) clearDeviceId {
  result.hasDeviceId = NO;
  result.deviceId = @"";
  return self;
}
@end

@interface CreateAccountViaNoCredentialsRequestProto ()
@property (retain) NSString* udid;
@property (retain) NSString* deviceId;
@property (retain) NSString* nameStrangersSee;
@end

@implementation CreateAccountViaNoCredentialsRequestProto

- (BOOL) hasUdid {
  return !!hasUdid_;
}
- (void) setHasUdid:(BOOL) value {
  hasUdid_ = !!value;
}
@synthesize udid;
- (BOOL) hasDeviceId {
  return !!hasDeviceId_;
}
- (void) setHasDeviceId:(BOOL) value {
  hasDeviceId_ = !!value;
}
@synthesize deviceId;
- (BOOL) hasNameStrangersSee {
  return !!hasNameStrangersSee_;
}
- (void) setHasNameStrangersSee:(BOOL) value {
  hasNameStrangersSee_ = !!value;
}
@synthesize nameStrangersSee;
- (void) dealloc {
  self.udid = nil;
  self.deviceId = nil;
  self.nameStrangersSee = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.udid = @"";
    self.deviceId = @"";
    self.nameStrangersSee = @"";
  }
  return self;
}
static CreateAccountViaNoCredentialsRequestProto* defaultCreateAccountViaNoCredentialsRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [CreateAccountViaNoCredentialsRequestProto class]) {
    defaultCreateAccountViaNoCredentialsRequestProtoInstance = [[CreateAccountViaNoCredentialsRequestProto alloc] init];
  }
}
+ (CreateAccountViaNoCredentialsRequestProto*) defaultInstance {
  return defaultCreateAccountViaNoCredentialsRequestProtoInstance;
}
- (CreateAccountViaNoCredentialsRequestProto*) defaultInstance {
  return defaultCreateAccountViaNoCredentialsRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUdid) {
    [output writeString:1 value:self.udid];
  }
  if (self.hasDeviceId) {
    [output writeString:2 value:self.deviceId];
  }
  if (self.hasNameStrangersSee) {
    [output writeString:3 value:self.nameStrangersSee];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUdid) {
    size += computeStringSize(1, self.udid);
  }
  if (self.hasDeviceId) {
    size += computeStringSize(2, self.deviceId);
  }
  if (self.hasNameStrangersSee) {
    size += computeStringSize(3, self.nameStrangersSee);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromData:(NSData*) data {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromData:data] build];
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromInputStream:input] build];
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (CreateAccountViaNoCredentialsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountViaNoCredentialsRequestProto*)[[[CreateAccountViaNoCredentialsRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountViaNoCredentialsRequestProto_Builder*) builder {
  return [[[CreateAccountViaNoCredentialsRequestProto_Builder alloc] init] autorelease];
}
+ (CreateAccountViaNoCredentialsRequestProto_Builder*) builderWithPrototype:(CreateAccountViaNoCredentialsRequestProto*) prototype {
  return [[CreateAccountViaNoCredentialsRequestProto builder] mergeFrom:prototype];
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) builder {
  return [CreateAccountViaNoCredentialsRequestProto builder];
}
@end

@interface CreateAccountViaNoCredentialsRequestProto_Builder()
@property (retain) CreateAccountViaNoCredentialsRequestProto* result;
@end

@implementation CreateAccountViaNoCredentialsRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CreateAccountViaNoCredentialsRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) clear {
  self.result = [[[CreateAccountViaNoCredentialsRequestProto alloc] init] autorelease];
  return self;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) clone {
  return [CreateAccountViaNoCredentialsRequestProto builderWithPrototype:result];
}
- (CreateAccountViaNoCredentialsRequestProto*) defaultInstance {
  return [CreateAccountViaNoCredentialsRequestProto defaultInstance];
}
- (CreateAccountViaNoCredentialsRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CreateAccountViaNoCredentialsRequestProto*) buildPartial {
  CreateAccountViaNoCredentialsRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) mergeFrom:(CreateAccountViaNoCredentialsRequestProto*) other {
  if (other == [CreateAccountViaNoCredentialsRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasUdid) {
    [self setUdid:other.udid];
  }
  if (other.hasDeviceId) {
    [self setDeviceId:other.deviceId];
  }
  if (other.hasNameStrangersSee) {
    [self setNameStrangersSee:other.nameStrangersSee];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUdid:[input readString]];
        break;
      }
      case 18: {
        [self setDeviceId:[input readString]];
        break;
      }
      case 26: {
        [self setNameStrangersSee:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasUdid {
  return result.hasUdid;
}
- (NSString*) udid {
  return result.udid;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) setUdid:(NSString*) value {
  result.hasUdid = YES;
  result.udid = value;
  return self;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) clearUdid {
  result.hasUdid = NO;
  result.udid = @"";
  return self;
}
- (BOOL) hasDeviceId {
  return result.hasDeviceId;
}
- (NSString*) deviceId {
  return result.deviceId;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) setDeviceId:(NSString*) value {
  result.hasDeviceId = YES;
  result.deviceId = value;
  return self;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) clearDeviceId {
  result.hasDeviceId = NO;
  result.deviceId = @"";
  return self;
}
- (BOOL) hasNameStrangersSee {
  return result.hasNameStrangersSee;
}
- (NSString*) nameStrangersSee {
  return result.nameStrangersSee;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) setNameStrangersSee:(NSString*) value {
  result.hasNameStrangersSee = YES;
  result.nameStrangersSee = value;
  return self;
}
- (CreateAccountViaNoCredentialsRequestProto_Builder*) clearNameStrangersSee {
  result.hasNameStrangersSee = NO;
  result.nameStrangersSee = @"";
  return self;
}
@end

@interface CreateAccountResponseProto ()
@property (retain) BasicUserProto* recipient;
@property CreateAccountResponseProto_CreateAccountStatus status;
@property (retain) NSMutableArray* mutableOtherNamesList;
@end

@implementation CreateAccountResponseProto

- (BOOL) hasRecipient {
  return !!hasRecipient_;
}
- (void) setHasRecipient:(BOOL) value {
  hasRecipient_ = !!value;
}
@synthesize recipient;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
@synthesize mutableOtherNamesList;
- (void) dealloc {
  self.recipient = nil;
  self.mutableOtherNamesList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.recipient = [BasicUserProto defaultInstance];
    self.status = CreateAccountResponseProto_CreateAccountStatusSuccessAccountCreated;
  }
  return self;
}
static CreateAccountResponseProto* defaultCreateAccountResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [CreateAccountResponseProto class]) {
    defaultCreateAccountResponseProtoInstance = [[CreateAccountResponseProto alloc] init];
  }
}
+ (CreateAccountResponseProto*) defaultInstance {
  return defaultCreateAccountResponseProtoInstance;
}
- (CreateAccountResponseProto*) defaultInstance {
  return defaultCreateAccountResponseProtoInstance;
}
- (NSArray*) otherNamesList {
  return mutableOtherNamesList;
}
- (NSString*) otherNamesAtIndex:(int32_t) index {
  id value = [mutableOtherNamesList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRecipient) {
    [output writeMessage:1 value:self.recipient];
  }
  if (self.hasStatus) {
    [output writeEnum:2 value:self.status];
  }
  for (NSString* element in self.mutableOtherNamesList) {
    [output writeString:3 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasRecipient) {
    size += computeMessageSize(1, self.recipient);
  }
  if (self.hasStatus) {
    size += computeEnumSize(2, self.status);
  }
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableOtherNamesList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableOtherNamesList.count;
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CreateAccountResponseProto*) parseFromData:(NSData*) data {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromData:data] build];
}
+ (CreateAccountResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromInputStream:input] build];
}
+ (CreateAccountResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (CreateAccountResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateAccountResponseProto*)[[[CreateAccountResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateAccountResponseProto_Builder*) builder {
  return [[[CreateAccountResponseProto_Builder alloc] init] autorelease];
}
+ (CreateAccountResponseProto_Builder*) builderWithPrototype:(CreateAccountResponseProto*) prototype {
  return [[CreateAccountResponseProto builder] mergeFrom:prototype];
}
- (CreateAccountResponseProto_Builder*) builder {
  return [CreateAccountResponseProto builder];
}
@end

BOOL CreateAccountResponseProto_CreateAccountStatusIsValidValue(CreateAccountResponseProto_CreateAccountStatus value) {
  switch (value) {
    case CreateAccountResponseProto_CreateAccountStatusSuccessAccountCreated:
    case CreateAccountResponseProto_CreateAccountStatusFailDuplicateFacebookId:
    case CreateAccountResponseProto_CreateAccountStatusFailDuplicateUdid:
    case CreateAccountResponseProto_CreateAccountStatusFailMissingFacebookId:
    case CreateAccountResponseProto_CreateAccountStatusFailInvalidName:
    case CreateAccountResponseProto_CreateAccountStatusFailInvalidUdid:
    case CreateAccountResponseProto_CreateAccountStatusFailInvalidPassword:
    case CreateAccountResponseProto_CreateAccountStatusFailOther:
    case CreateAccountResponseProto_CreateAccountStatusFailDuplicateEmail:
    case CreateAccountResponseProto_CreateAccountStatusFailInvalidEmail:
    case CreateAccountResponseProto_CreateAccountStatusFailDuplicateName:
      return YES;
    default:
      return NO;
  }
}
@interface CreateAccountResponseProto_Builder()
@property (retain) CreateAccountResponseProto* result;
@end

@implementation CreateAccountResponseProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CreateAccountResponseProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CreateAccountResponseProto_Builder*) clear {
  self.result = [[[CreateAccountResponseProto alloc] init] autorelease];
  return self;
}
- (CreateAccountResponseProto_Builder*) clone {
  return [CreateAccountResponseProto builderWithPrototype:result];
}
- (CreateAccountResponseProto*) defaultInstance {
  return [CreateAccountResponseProto defaultInstance];
}
- (CreateAccountResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CreateAccountResponseProto*) buildPartial {
  CreateAccountResponseProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CreateAccountResponseProto_Builder*) mergeFrom:(CreateAccountResponseProto*) other {
  if (other == [CreateAccountResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasRecipient) {
    [self mergeRecipient:other.recipient];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.mutableOtherNamesList.count > 0) {
    if (result.mutableOtherNamesList == nil) {
      result.mutableOtherNamesList = [NSMutableArray array];
    }
    [result.mutableOtherNamesList addObjectsFromArray:other.mutableOtherNamesList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CreateAccountResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CreateAccountResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        BasicUserProto_Builder* subBuilder = [BasicUserProto builder];
        if (self.hasRecipient) {
          [subBuilder mergeFrom:self.recipient];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRecipient:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        int32_t value = [input readEnum];
        if (CreateAccountResponseProto_CreateAccountStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 26: {
        [self addOtherNames:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasRecipient {
  return result.hasRecipient;
}
- (BasicUserProto*) recipient {
  return result.recipient;
}
- (CreateAccountResponseProto_Builder*) setRecipient:(BasicUserProto*) value {
  result.hasRecipient = YES;
  result.recipient = value;
  return self;
}
- (CreateAccountResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue {
  return [self setRecipient:[builderForValue build]];
}
- (CreateAccountResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value {
  if (result.hasRecipient &&
      result.recipient != [BasicUserProto defaultInstance]) {
    result.recipient =
      [[[BasicUserProto builderWithPrototype:result.recipient] mergeFrom:value] buildPartial];
  } else {
    result.recipient = value;
  }
  result.hasRecipient = YES;
  return self;
}
- (CreateAccountResponseProto_Builder*) clearRecipient {
  result.hasRecipient = NO;
  result.recipient = [BasicUserProto defaultInstance];
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (CreateAccountResponseProto_CreateAccountStatus) status {
  return result.status;
}
- (CreateAccountResponseProto_Builder*) setStatus:(CreateAccountResponseProto_CreateAccountStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (CreateAccountResponseProto_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = CreateAccountResponseProto_CreateAccountStatusSuccessAccountCreated;
  return self;
}
- (NSArray*) otherNamesList {
  if (result.mutableOtherNamesList == nil) {
    return [NSArray array];
  }
  return result.mutableOtherNamesList;
}
- (NSString*) otherNamesAtIndex:(int32_t) index {
  return [result otherNamesAtIndex:index];
}
- (CreateAccountResponseProto_Builder*) replaceOtherNamesAtIndex:(int32_t) index with:(NSString*) value {
  [result.mutableOtherNamesList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (CreateAccountResponseProto_Builder*) addOtherNames:(NSString*) value {
  if (result.mutableOtherNamesList == nil) {
    result.mutableOtherNamesList = [NSMutableArray array];
  }
  [result.mutableOtherNamesList addObject:value];
  return self;
}
- (CreateAccountResponseProto_Builder*) addAllOtherNames:(NSArray*) values {
  if (result.mutableOtherNamesList == nil) {
    result.mutableOtherNamesList = [NSMutableArray array];
  }
  [result.mutableOtherNamesList addObjectsFromArray:values];
  return self;
}
- (CreateAccountResponseProto_Builder*) clearOtherNamesList {
  result.mutableOtherNamesList = nil;
  return self;
}
@end

