// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "InAppPurchaseEvent.pb.h"

@implementation InAppPurchaseEventRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [InAppPurchaseEventRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface InAppPurchaseRequestProto ()
@property (retain) BasicUserProto* sender;
@property (retain) NSString* receipt;
@property (retain) NSString* localcents;
@property (retain) NSString* localcurrency;
@property (retain) NSString* locale;
@property (retain) NSString* ipaddr;
@end

@implementation InAppPurchaseRequestProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value {
  hasSender_ = !!value;
}
@synthesize sender;
- (BOOL) hasReceipt {
  return !!hasReceipt_;
}
- (void) setHasReceipt:(BOOL) value {
  hasReceipt_ = !!value;
}
@synthesize receipt;
- (BOOL) hasLocalcents {
  return !!hasLocalcents_;
}
- (void) setHasLocalcents:(BOOL) value {
  hasLocalcents_ = !!value;
}
@synthesize localcents;
- (BOOL) hasLocalcurrency {
  return !!hasLocalcurrency_;
}
- (void) setHasLocalcurrency:(BOOL) value {
  hasLocalcurrency_ = !!value;
}
@synthesize localcurrency;
- (BOOL) hasLocale {
  return !!hasLocale_;
}
- (void) setHasLocale:(BOOL) value {
  hasLocale_ = !!value;
}
@synthesize locale;
- (BOOL) hasIpaddr {
  return !!hasIpaddr_;
}
- (void) setHasIpaddr:(BOOL) value {
  hasIpaddr_ = !!value;
}
@synthesize ipaddr;
- (void) dealloc {
  self.sender = nil;
  self.receipt = nil;
  self.localcents = nil;
  self.localcurrency = nil;
  self.locale = nil;
  self.ipaddr = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sender = [BasicUserProto defaultInstance];
    self.receipt = @"";
    self.localcents = @"";
    self.localcurrency = @"";
    self.locale = @"";
    self.ipaddr = @"";
  }
  return self;
}
static InAppPurchaseRequestProto* defaultInAppPurchaseRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [InAppPurchaseRequestProto class]) {
    defaultInAppPurchaseRequestProtoInstance = [[InAppPurchaseRequestProto alloc] init];
  }
}
+ (InAppPurchaseRequestProto*) defaultInstance {
  return defaultInAppPurchaseRequestProtoInstance;
}
- (InAppPurchaseRequestProto*) defaultInstance {
  return defaultInAppPurchaseRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasReceipt) {
    [output writeString:2 value:self.receipt];
  }
  if (self.hasLocalcents) {
    [output writeString:3 value:self.localcents];
  }
  if (self.hasLocalcurrency) {
    [output writeString:4 value:self.localcurrency];
  }
  if (self.hasLocale) {
    [output writeString:5 value:self.locale];
  }
  if (self.hasIpaddr) {
    [output writeString:6 value:self.ipaddr];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSender) {
    size += computeMessageSize(1, self.sender);
  }
  if (self.hasReceipt) {
    size += computeStringSize(2, self.receipt);
  }
  if (self.hasLocalcents) {
    size += computeStringSize(3, self.localcents);
  }
  if (self.hasLocalcurrency) {
    size += computeStringSize(4, self.localcurrency);
  }
  if (self.hasLocale) {
    size += computeStringSize(5, self.locale);
  }
  if (self.hasIpaddr) {
    size += computeStringSize(6, self.ipaddr);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (InAppPurchaseRequestProto*) parseFromData:(NSData*) data {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromData:data] build];
}
+ (InAppPurchaseRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromInputStream:input] build];
}
+ (InAppPurchaseRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (InAppPurchaseRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseRequestProto*)[[[InAppPurchaseRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseRequestProto_Builder*) builder {
  return [[[InAppPurchaseRequestProto_Builder alloc] init] autorelease];
}
+ (InAppPurchaseRequestProto_Builder*) builderWithPrototype:(InAppPurchaseRequestProto*) prototype {
  return [[InAppPurchaseRequestProto builder] mergeFrom:prototype];
}
- (InAppPurchaseRequestProto_Builder*) builder {
  return [InAppPurchaseRequestProto builder];
}
@end

@interface InAppPurchaseRequestProto_Builder()
@property (retain) InAppPurchaseRequestProto* result;
@end

@implementation InAppPurchaseRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[InAppPurchaseRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (InAppPurchaseRequestProto_Builder*) clear {
  self.result = [[[InAppPurchaseRequestProto alloc] init] autorelease];
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clone {
  return [InAppPurchaseRequestProto builderWithPrototype:result];
}
- (InAppPurchaseRequestProto*) defaultInstance {
  return [InAppPurchaseRequestProto defaultInstance];
}
- (InAppPurchaseRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (InAppPurchaseRequestProto*) buildPartial {
  InAppPurchaseRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (InAppPurchaseRequestProto_Builder*) mergeFrom:(InAppPurchaseRequestProto*) other {
  if (other == [InAppPurchaseRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasReceipt) {
    [self setReceipt:other.receipt];
  }
  if (other.hasLocalcents) {
    [self setLocalcents:other.localcents];
  }
  if (other.hasLocalcurrency) {
    [self setLocalcurrency:other.localcurrency];
  }
  if (other.hasLocale) {
    [self setLocale:other.locale];
  }
  if (other.hasIpaddr) {
    [self setIpaddr:other.ipaddr];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (InAppPurchaseRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (InAppPurchaseRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        BasicUserProto_Builder* subBuilder = [BasicUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setReceipt:[input readString]];
        break;
      }
      case 26: {
        [self setLocalcents:[input readString]];
        break;
      }
      case 34: {
        [self setLocalcurrency:[input readString]];
        break;
      }
      case 42: {
        [self setLocale:[input readString]];
        break;
      }
      case 50: {
        [self setIpaddr:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (BasicUserProto*) sender {
  return result.sender;
}
- (InAppPurchaseRequestProto_Builder*) setSender:(BasicUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (InAppPurchaseRequestProto_Builder*) mergeSender:(BasicUserProto*) value {
  if (result.hasSender &&
      result.sender != [BasicUserProto defaultInstance]) {
    result.sender =
      [[[BasicUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [BasicUserProto defaultInstance];
  return self;
}
- (BOOL) hasReceipt {
  return result.hasReceipt;
}
- (NSString*) receipt {
  return result.receipt;
}
- (InAppPurchaseRequestProto_Builder*) setReceipt:(NSString*) value {
  result.hasReceipt = YES;
  result.receipt = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearReceipt {
  result.hasReceipt = NO;
  result.receipt = @"";
  return self;
}
- (BOOL) hasLocalcents {
  return result.hasLocalcents;
}
- (NSString*) localcents {
  return result.localcents;
}
- (InAppPurchaseRequestProto_Builder*) setLocalcents:(NSString*) value {
  result.hasLocalcents = YES;
  result.localcents = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearLocalcents {
  result.hasLocalcents = NO;
  result.localcents = @"";
  return self;
}
- (BOOL) hasLocalcurrency {
  return result.hasLocalcurrency;
}
- (NSString*) localcurrency {
  return result.localcurrency;
}
- (InAppPurchaseRequestProto_Builder*) setLocalcurrency:(NSString*) value {
  result.hasLocalcurrency = YES;
  result.localcurrency = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearLocalcurrency {
  result.hasLocalcurrency = NO;
  result.localcurrency = @"";
  return self;
}
- (BOOL) hasLocale {
  return result.hasLocale;
}
- (NSString*) locale {
  return result.locale;
}
- (InAppPurchaseRequestProto_Builder*) setLocale:(NSString*) value {
  result.hasLocale = YES;
  result.locale = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearLocale {
  result.hasLocale = NO;
  result.locale = @"";
  return self;
}
- (BOOL) hasIpaddr {
  return result.hasIpaddr;
}
- (NSString*) ipaddr {
  return result.ipaddr;
}
- (InAppPurchaseRequestProto_Builder*) setIpaddr:(NSString*) value {
  result.hasIpaddr = YES;
  result.ipaddr = value;
  return self;
}
- (InAppPurchaseRequestProto_Builder*) clearIpaddr {
  result.hasIpaddr = NO;
  result.ipaddr = @"";
  return self;
}
@end

@interface InAppPurchaseResponseProto ()
@property (retain) BasicUserProto* sender;
@property InAppPurchaseResponseProto_InAppPurchaseStatus status;
@property int32_t rubiesGained;
@property int32_t tokensGained;
@property (retain) NSString* packageName;
@property Float64 packagePrice;
@property (retain) NSString* receipt;
@end

@implementation InAppPurchaseResponseProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value {
  hasSender_ = !!value;
}
@synthesize sender;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (BOOL) hasRubiesGained {
  return !!hasRubiesGained_;
}
- (void) setHasRubiesGained:(BOOL) value {
  hasRubiesGained_ = !!value;
}
@synthesize rubiesGained;
- (BOOL) hasTokensGained {
  return !!hasTokensGained_;
}
- (void) setHasTokensGained:(BOOL) value {
  hasTokensGained_ = !!value;
}
@synthesize tokensGained;
- (BOOL) hasPackageName {
  return !!hasPackageName_;
}
- (void) setHasPackageName:(BOOL) value {
  hasPackageName_ = !!value;
}
@synthesize packageName;
- (BOOL) hasPackagePrice {
  return !!hasPackagePrice_;
}
- (void) setHasPackagePrice:(BOOL) value {
  hasPackagePrice_ = !!value;
}
@synthesize packagePrice;
- (BOOL) hasReceipt {
  return !!hasReceipt_;
}
- (void) setHasReceipt:(BOOL) value {
  hasReceipt_ = !!value;
}
@synthesize receipt;
- (void) dealloc {
  self.sender = nil;
  self.packageName = nil;
  self.receipt = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sender = [BasicUserProto defaultInstance];
    self.status = InAppPurchaseResponseProto_InAppPurchaseStatusSuccess;
    self.rubiesGained = 0;
    self.tokensGained = 0;
    self.packageName = @"";
    self.packagePrice = 0;
    self.receipt = @"";
  }
  return self;
}
static InAppPurchaseResponseProto* defaultInAppPurchaseResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [InAppPurchaseResponseProto class]) {
    defaultInAppPurchaseResponseProtoInstance = [[InAppPurchaseResponseProto alloc] init];
  }
}
+ (InAppPurchaseResponseProto*) defaultInstance {
  return defaultInAppPurchaseResponseProtoInstance;
}
- (InAppPurchaseResponseProto*) defaultInstance {
  return defaultInAppPurchaseResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasStatus) {
    [output writeEnum:2 value:self.status];
  }
  if (self.hasRubiesGained) {
    [output writeInt32:3 value:self.rubiesGained];
  }
  if (self.hasPackageName) {
    [output writeString:4 value:self.packageName];
  }
  if (self.hasPackagePrice) {
    [output writeDouble:5 value:self.packagePrice];
  }
  if (self.hasReceipt) {
    [output writeString:6 value:self.receipt];
  }
  if (self.hasTokensGained) {
    [output writeInt32:7 value:self.tokensGained];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSender) {
    size += computeMessageSize(1, self.sender);
  }
  if (self.hasStatus) {
    size += computeEnumSize(2, self.status);
  }
  if (self.hasRubiesGained) {
    size += computeInt32Size(3, self.rubiesGained);
  }
  if (self.hasPackageName) {
    size += computeStringSize(4, self.packageName);
  }
  if (self.hasPackagePrice) {
    size += computeDoubleSize(5, self.packagePrice);
  }
  if (self.hasReceipt) {
    size += computeStringSize(6, self.receipt);
  }
  if (self.hasTokensGained) {
    size += computeInt32Size(7, self.tokensGained);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (InAppPurchaseResponseProto*) parseFromData:(NSData*) data {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromData:data] build];
}
+ (InAppPurchaseResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromInputStream:input] build];
}
+ (InAppPurchaseResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (InAppPurchaseResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (InAppPurchaseResponseProto*)[[[InAppPurchaseResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (InAppPurchaseResponseProto_Builder*) builder {
  return [[[InAppPurchaseResponseProto_Builder alloc] init] autorelease];
}
+ (InAppPurchaseResponseProto_Builder*) builderWithPrototype:(InAppPurchaseResponseProto*) prototype {
  return [[InAppPurchaseResponseProto builder] mergeFrom:prototype];
}
- (InAppPurchaseResponseProto_Builder*) builder {
  return [InAppPurchaseResponseProto builder];
}
@end

BOOL InAppPurchaseResponseProto_InAppPurchaseStatusIsValidValue(InAppPurchaseResponseProto_InAppPurchaseStatus value) {
  switch (value) {
    case InAppPurchaseResponseProto_InAppPurchaseStatusSuccess:
    case InAppPurchaseResponseProto_InAppPurchaseStatusFailOther:
    case InAppPurchaseResponseProto_InAppPurchaseStatusFailDuplicateReceipt:
      return YES;
    default:
      return NO;
  }
}
@interface InAppPurchaseResponseProto_Builder()
@property (retain) InAppPurchaseResponseProto* result;
@end

@implementation InAppPurchaseResponseProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[InAppPurchaseResponseProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (InAppPurchaseResponseProto_Builder*) clear {
  self.result = [[[InAppPurchaseResponseProto alloc] init] autorelease];
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clone {
  return [InAppPurchaseResponseProto builderWithPrototype:result];
}
- (InAppPurchaseResponseProto*) defaultInstance {
  return [InAppPurchaseResponseProto defaultInstance];
}
- (InAppPurchaseResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (InAppPurchaseResponseProto*) buildPartial {
  InAppPurchaseResponseProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (InAppPurchaseResponseProto_Builder*) mergeFrom:(InAppPurchaseResponseProto*) other {
  if (other == [InAppPurchaseResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasRubiesGained) {
    [self setRubiesGained:other.rubiesGained];
  }
  if (other.hasTokensGained) {
    [self setTokensGained:other.tokensGained];
  }
  if (other.hasPackageName) {
    [self setPackageName:other.packageName];
  }
  if (other.hasPackagePrice) {
    [self setPackagePrice:other.packagePrice];
  }
  if (other.hasReceipt) {
    [self setReceipt:other.receipt];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (InAppPurchaseResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (InAppPurchaseResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        BasicUserProto_Builder* subBuilder = [BasicUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        int32_t value = [input readEnum];
        if (InAppPurchaseResponseProto_InAppPurchaseStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 24: {
        [self setRubiesGained:[input readInt32]];
        break;
      }
      case 34: {
        [self setPackageName:[input readString]];
        break;
      }
      case 41: {
        [self setPackagePrice:[input readDouble]];
        break;
      }
      case 50: {
        [self setReceipt:[input readString]];
        break;
      }
      case 56: {
        [self setTokensGained:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (BasicUserProto*) sender {
  return result.sender;
}
- (InAppPurchaseResponseProto_Builder*) setSender:(BasicUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (InAppPurchaseResponseProto_Builder*) mergeSender:(BasicUserProto*) value {
  if (result.hasSender &&
      result.sender != [BasicUserProto defaultInstance]) {
    result.sender =
      [[[BasicUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [BasicUserProto defaultInstance];
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (InAppPurchaseResponseProto_InAppPurchaseStatus) status {
  return result.status;
}
- (InAppPurchaseResponseProto_Builder*) setStatus:(InAppPurchaseResponseProto_InAppPurchaseStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = InAppPurchaseResponseProto_InAppPurchaseStatusSuccess;
  return self;
}
- (BOOL) hasRubiesGained {
  return result.hasRubiesGained;
}
- (int32_t) rubiesGained {
  return result.rubiesGained;
}
- (InAppPurchaseResponseProto_Builder*) setRubiesGained:(int32_t) value {
  result.hasRubiesGained = YES;
  result.rubiesGained = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearRubiesGained {
  result.hasRubiesGained = NO;
  result.rubiesGained = 0;
  return self;
}
- (BOOL) hasTokensGained {
  return result.hasTokensGained;
}
- (int32_t) tokensGained {
  return result.tokensGained;
}
- (InAppPurchaseResponseProto_Builder*) setTokensGained:(int32_t) value {
  result.hasTokensGained = YES;
  result.tokensGained = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearTokensGained {
  result.hasTokensGained = NO;
  result.tokensGained = 0;
  return self;
}
- (BOOL) hasPackageName {
  return result.hasPackageName;
}
- (NSString*) packageName {
  return result.packageName;
}
- (InAppPurchaseResponseProto_Builder*) setPackageName:(NSString*) value {
  result.hasPackageName = YES;
  result.packageName = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearPackageName {
  result.hasPackageName = NO;
  result.packageName = @"";
  return self;
}
- (BOOL) hasPackagePrice {
  return result.hasPackagePrice;
}
- (Float64) packagePrice {
  return result.packagePrice;
}
- (InAppPurchaseResponseProto_Builder*) setPackagePrice:(Float64) value {
  result.hasPackagePrice = YES;
  result.packagePrice = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearPackagePrice {
  result.hasPackagePrice = NO;
  result.packagePrice = 0;
  return self;
}
- (BOOL) hasReceipt {
  return result.hasReceipt;
}
- (NSString*) receipt {
  return result.receipt;
}
- (InAppPurchaseResponseProto_Builder*) setReceipt:(NSString*) value {
  result.hasReceipt = YES;
  result.receipt = value;
  return self;
}
- (InAppPurchaseResponseProto_Builder*) clearReceipt {
  result.hasReceipt = NO;
  result.receipt = @"";
  return self;
}
@end

