// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "User.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class LogoutRequestProto;
@class LogoutRequestProto_Builder;
@class UserCurrencyProto;
@class UserCurrencyProto_Builder;

@interface LogoutRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface LogoutRequestProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BasicUserProto* sender;
}
- (BOOL) hasSender;
@property (readonly, retain) BasicUserProto* sender;

+ (LogoutRequestProto*) defaultInstance;
- (LogoutRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LogoutRequestProto_Builder*) builder;
+ (LogoutRequestProto_Builder*) builder;
+ (LogoutRequestProto_Builder*) builderWithPrototype:(LogoutRequestProto*) prototype;

+ (LogoutRequestProto*) parseFromData:(NSData*) data;
+ (LogoutRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LogoutRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (LogoutRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LogoutRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LogoutRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LogoutRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  LogoutRequestProto* result;
}

- (LogoutRequestProto*) defaultInstance;

- (LogoutRequestProto_Builder*) clear;
- (LogoutRequestProto_Builder*) clone;

- (LogoutRequestProto*) build;
- (LogoutRequestProto*) buildPartial;

- (LogoutRequestProto_Builder*) mergeFrom:(LogoutRequestProto*) other;
- (LogoutRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LogoutRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (LogoutRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (LogoutRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (LogoutRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (LogoutRequestProto_Builder*) clearSender;
@end

