// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "User.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class RefillTokensByWaitingRequestProto;
@class RefillTokensByWaitingRequestProto_Builder;
@class RefillTokensByWaitingResponseProto;
@class RefillTokensByWaitingResponseProto_Builder;
@class UserCurrencyProto;
@class UserCurrencyProto_Builder;
typedef enum {
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusSuccess = 1,
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusFailNotReadyYet = 2,
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusFailAlreadyMax = 3,
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusFailClientTooApartFromServerTime = 4,
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusFailOther = 5,
} RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus;

BOOL RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatusIsValidValue(RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus value);


@interface RefillTokensByWaitingEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RefillTokensByWaitingRequestProto : PBGeneratedMessage {
@private
  BOOL hasCurTime_:1;
  BOOL hasSender_:1;
  int64_t curTime;
  BasicUserProto* sender;
}
- (BOOL) hasSender;
- (BOOL) hasCurTime;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly) int64_t curTime;

+ (RefillTokensByWaitingRequestProto*) defaultInstance;
- (RefillTokensByWaitingRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefillTokensByWaitingRequestProto_Builder*) builder;
+ (RefillTokensByWaitingRequestProto_Builder*) builder;
+ (RefillTokensByWaitingRequestProto_Builder*) builderWithPrototype:(RefillTokensByWaitingRequestProto*) prototype;

+ (RefillTokensByWaitingRequestProto*) parseFromData:(NSData*) data;
+ (RefillTokensByWaitingRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefillTokensByWaitingRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (RefillTokensByWaitingRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefillTokensByWaitingRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefillTokensByWaitingRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RefillTokensByWaitingRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  RefillTokensByWaitingRequestProto* result;
}

- (RefillTokensByWaitingRequestProto*) defaultInstance;

- (RefillTokensByWaitingRequestProto_Builder*) clear;
- (RefillTokensByWaitingRequestProto_Builder*) clone;

- (RefillTokensByWaitingRequestProto*) build;
- (RefillTokensByWaitingRequestProto*) buildPartial;

- (RefillTokensByWaitingRequestProto_Builder*) mergeFrom:(RefillTokensByWaitingRequestProto*) other;
- (RefillTokensByWaitingRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefillTokensByWaitingRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (RefillTokensByWaitingRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (RefillTokensByWaitingRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (RefillTokensByWaitingRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (RefillTokensByWaitingRequestProto_Builder*) clearSender;

- (BOOL) hasCurTime;
- (int64_t) curTime;
- (RefillTokensByWaitingRequestProto_Builder*) setCurTime:(int64_t) value;
- (RefillTokensByWaitingRequestProto_Builder*) clearCurTime;
@end

@interface RefillTokensByWaitingResponseProto : PBGeneratedMessage {
@private
  BOOL hasRecipient_:1;
  BOOL hasStatus_:1;
  BasicUserProto* recipient;
  RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus status;
}
- (BOOL) hasRecipient;
- (BOOL) hasStatus;
@property (readonly, retain) BasicUserProto* recipient;
@property (readonly) RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus status;

+ (RefillTokensByWaitingResponseProto*) defaultInstance;
- (RefillTokensByWaitingResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefillTokensByWaitingResponseProto_Builder*) builder;
+ (RefillTokensByWaitingResponseProto_Builder*) builder;
+ (RefillTokensByWaitingResponseProto_Builder*) builderWithPrototype:(RefillTokensByWaitingResponseProto*) prototype;

+ (RefillTokensByWaitingResponseProto*) parseFromData:(NSData*) data;
+ (RefillTokensByWaitingResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefillTokensByWaitingResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (RefillTokensByWaitingResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefillTokensByWaitingResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefillTokensByWaitingResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RefillTokensByWaitingResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  RefillTokensByWaitingResponseProto* result;
}

- (RefillTokensByWaitingResponseProto*) defaultInstance;

- (RefillTokensByWaitingResponseProto_Builder*) clear;
- (RefillTokensByWaitingResponseProto_Builder*) clone;

- (RefillTokensByWaitingResponseProto*) build;
- (RefillTokensByWaitingResponseProto*) buildPartial;

- (RefillTokensByWaitingResponseProto_Builder*) mergeFrom:(RefillTokensByWaitingResponseProto*) other;
- (RefillTokensByWaitingResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefillTokensByWaitingResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (RefillTokensByWaitingResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (RefillTokensByWaitingResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (RefillTokensByWaitingResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (RefillTokensByWaitingResponseProto_Builder*) clearRecipient;

- (BOOL) hasStatus;
- (RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus) status;
- (RefillTokensByWaitingResponseProto_Builder*) setStatus:(RefillTokensByWaitingResponseProto_RefillTokensByWaitingStatus) value;
- (RefillTokensByWaitingResponseProto_Builder*) clearStatus;
@end

