// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "User.pb.h"
#import "TriviaQuestionFormat.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
@class RetrieveNewQuestionsRequestProto;
@class RetrieveNewQuestionsRequestProto_Builder;
@class RetrieveNewQuestionsResponseProto;
@class RetrieveNewQuestionsResponseProto_Builder;
typedef enum {
  RetrieveNewQuestionsResponseProto_RetrieveNewQuestionsResponseStatusSuccess = 1,
  RetrieveNewQuestionsResponseProto_RetrieveNewQuestionsResponseStatusFailOther = 2,
} RetrieveNewQuestionsResponseProto_RetrieveNewQuestionsResponseStatus;

BOOL RetrieveNewQuestionsResponseProto_RetrieveNewQuestionsResponseStatusIsValidValue(RetrieveNewQuestionsResponseProto_RetrieveNewQuestionsResponseStatus value);


@interface RetrieveNewQuestionsEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RetrieveNewQuestionsRequestProto : PBGeneratedMessage {
@private
  BOOL hasNumQuestionsWanted_:1;
  BOOL hasSender_:1;
  int32_t numQuestionsWanted;
  BasicUserProto* sender;
}
- (BOOL) hasSender;
- (BOOL) hasNumQuestionsWanted;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly) int32_t numQuestionsWanted;

+ (RetrieveNewQuestionsRequestProto*) defaultInstance;
- (RetrieveNewQuestionsRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveNewQuestionsRequestProto_Builder*) builder;
+ (RetrieveNewQuestionsRequestProto_Builder*) builder;
+ (RetrieveNewQuestionsRequestProto_Builder*) builderWithPrototype:(RetrieveNewQuestionsRequestProto*) prototype;

+ (RetrieveNewQuestionsRequestProto*) parseFromData:(NSData*) data;
+ (RetrieveNewQuestionsRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveNewQuestionsRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveNewQuestionsRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveNewQuestionsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveNewQuestionsRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveNewQuestionsRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  RetrieveNewQuestionsRequestProto* result;
}

- (RetrieveNewQuestionsRequestProto*) defaultInstance;

- (RetrieveNewQuestionsRequestProto_Builder*) clear;
- (RetrieveNewQuestionsRequestProto_Builder*) clone;

- (RetrieveNewQuestionsRequestProto*) build;
- (RetrieveNewQuestionsRequestProto*) buildPartial;

- (RetrieveNewQuestionsRequestProto_Builder*) mergeFrom:(RetrieveNewQuestionsRequestProto*) other;
- (RetrieveNewQuestionsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveNewQuestionsRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (RetrieveNewQuestionsRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (RetrieveNewQuestionsRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (RetrieveNewQuestionsRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (RetrieveNewQuestionsRequestProto_Builder*) clearSender;

- (BOOL) hasNumQuestionsWanted;
- (int32_t) numQuestionsWanted;
- (RetrieveNewQuestionsRequestProto_Builder*) setNumQuestionsWanted:(int32_t) value;
- (RetrieveNewQuestionsRequestProto_Builder*) clearNumQuestionsWanted;
@end

@interface RetrieveNewQuestionsResponseProto : PBGeneratedMessage {
@private
  BOOL hasRecipient_:1;
  BasicUserProto* recipient;
  NSMutableArray* mutableNewQuestionsList;
}
- (BOOL) hasRecipient;
@property (readonly, retain) BasicUserProto* recipient;
- (NSArray*) newQuestionsList;
- (QuestionProto*) newQuestionsAtIndex:(int32_t) index;

+ (RetrieveNewQuestionsResponseProto*) defaultInstance;
- (RetrieveNewQuestionsResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveNewQuestionsResponseProto_Builder*) builder;
+ (RetrieveNewQuestionsResponseProto_Builder*) builder;
+ (RetrieveNewQuestionsResponseProto_Builder*) builderWithPrototype:(RetrieveNewQuestionsResponseProto*) prototype;

+ (RetrieveNewQuestionsResponseProto*) parseFromData:(NSData*) data;
+ (RetrieveNewQuestionsResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveNewQuestionsResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveNewQuestionsResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveNewQuestionsResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveNewQuestionsResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveNewQuestionsResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  RetrieveNewQuestionsResponseProto* result;
}

- (RetrieveNewQuestionsResponseProto*) defaultInstance;

- (RetrieveNewQuestionsResponseProto_Builder*) clear;
- (RetrieveNewQuestionsResponseProto_Builder*) clone;

- (RetrieveNewQuestionsResponseProto*) build;
- (RetrieveNewQuestionsResponseProto*) buildPartial;

- (RetrieveNewQuestionsResponseProto_Builder*) mergeFrom:(RetrieveNewQuestionsResponseProto*) other;
- (RetrieveNewQuestionsResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveNewQuestionsResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (RetrieveNewQuestionsResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (RetrieveNewQuestionsResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (RetrieveNewQuestionsResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (RetrieveNewQuestionsResponseProto_Builder*) clearRecipient;

- (NSArray*) newQuestionsList;
- (QuestionProto*) newQuestionsAtIndex:(int32_t) index;
- (RetrieveNewQuestionsResponseProto_Builder*) replaceNewQuestionsAtIndex:(int32_t) index with:(QuestionProto*) value;
- (RetrieveNewQuestionsResponseProto_Builder*) addNewQuestions:(QuestionProto*) value;
- (RetrieveNewQuestionsResponseProto_Builder*) addAllNewQuestions:(NSArray*) values;
- (RetrieveNewQuestionsResponseProto_Builder*) clearNewQuestionsList;
@end

