// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "TriviaGameFormat.pb.h"
#import "User.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicRoundResultsProto;
@class BasicRoundResultsProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteRoundResultsProto;
@class CompleteRoundResultsProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class GameResultsProto;
@class GameResultsProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class OngoingGameProto;
@class OngoingGameProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class PlayerGameResultsProto;
@class PlayerGameResultsProto_Builder;
@class QuestionAnsweredProto;
@class QuestionAnsweredProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
@class RetrieveUserGamesRequestProto;
@class RetrieveUserGamesRequestProto_Builder;
@class RetrieveUserGamesResponseProto;
@class RetrieveUserGamesResponseProto_Builder;
@class UnfinishedRoundProto;
@class UnfinishedRoundProto_Builder;
@class UserCurrencyProto;
@class UserCurrencyProto_Builder;
typedef enum {
  RetrieveUserGamesResponseProto_RetrieveUserGamesStatusSuccess = 1,
  RetrieveUserGamesResponseProto_RetrieveUserGamesStatusFailOther = 2,
} RetrieveUserGamesResponseProto_RetrieveUserGamesStatus;

BOOL RetrieveUserGamesResponseProto_RetrieveUserGamesStatusIsValidValue(RetrieveUserGamesResponseProto_RetrieveUserGamesStatus value);


@interface RetrieveUserGamesEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RetrieveUserGamesRequestProto : PBGeneratedMessage {
@private
  BOOL hasTimeForCompletedGames_:1;
  BOOL hasSender_:1;
  int64_t timeForCompletedGames;
  BasicUserProto* sender;
}
- (BOOL) hasSender;
- (BOOL) hasTimeForCompletedGames;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly) int64_t timeForCompletedGames;

+ (RetrieveUserGamesRequestProto*) defaultInstance;
- (RetrieveUserGamesRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveUserGamesRequestProto_Builder*) builder;
+ (RetrieveUserGamesRequestProto_Builder*) builder;
+ (RetrieveUserGamesRequestProto_Builder*) builderWithPrototype:(RetrieveUserGamesRequestProto*) prototype;

+ (RetrieveUserGamesRequestProto*) parseFromData:(NSData*) data;
+ (RetrieveUserGamesRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveUserGamesRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveUserGamesRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveUserGamesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveUserGamesRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveUserGamesRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  RetrieveUserGamesRequestProto* result;
}

- (RetrieveUserGamesRequestProto*) defaultInstance;

- (RetrieveUserGamesRequestProto_Builder*) clear;
- (RetrieveUserGamesRequestProto_Builder*) clone;

- (RetrieveUserGamesRequestProto*) build;
- (RetrieveUserGamesRequestProto*) buildPartial;

- (RetrieveUserGamesRequestProto_Builder*) mergeFrom:(RetrieveUserGamesRequestProto*) other;
- (RetrieveUserGamesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveUserGamesRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (RetrieveUserGamesRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (RetrieveUserGamesRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (RetrieveUserGamesRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (RetrieveUserGamesRequestProto_Builder*) clearSender;

- (BOOL) hasTimeForCompletedGames;
- (int64_t) timeForCompletedGames;
- (RetrieveUserGamesRequestProto_Builder*) setTimeForCompletedGames:(int64_t) value;
- (RetrieveUserGamesRequestProto_Builder*) clearTimeForCompletedGames;
@end

@interface RetrieveUserGamesResponseProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BOOL hasStatus_:1;
  BasicUserProto* sender;
  RetrieveUserGamesResponseProto_RetrieveUserGamesStatus status;
  NSMutableArray* mutablePictureNamesList;
  NSMutableArray* mutableCompletedGamesList;
  NSMutableArray* mutableMyTurnList;
  NSMutableArray* mutableNotMyTurnList;
}
- (BOOL) hasSender;
- (BOOL) hasStatus;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly) RetrieveUserGamesResponseProto_RetrieveUserGamesStatus status;
- (NSArray*) completedGamesList;
- (GameResultsProto*) completedGamesAtIndex:(int32_t) index;
- (NSArray*) myTurnList;
- (OngoingGameProto*) myTurnAtIndex:(int32_t) index;
- (NSArray*) notMyTurnList;
- (OngoingGameProto*) notMyTurnAtIndex:(int32_t) index;
- (NSArray*) pictureNamesList;
- (NSString*) pictureNamesAtIndex:(int32_t) index;

+ (RetrieveUserGamesResponseProto*) defaultInstance;
- (RetrieveUserGamesResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetrieveUserGamesResponseProto_Builder*) builder;
+ (RetrieveUserGamesResponseProto_Builder*) builder;
+ (RetrieveUserGamesResponseProto_Builder*) builderWithPrototype:(RetrieveUserGamesResponseProto*) prototype;

+ (RetrieveUserGamesResponseProto*) parseFromData:(NSData*) data;
+ (RetrieveUserGamesResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveUserGamesResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (RetrieveUserGamesResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetrieveUserGamesResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetrieveUserGamesResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetrieveUserGamesResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  RetrieveUserGamesResponseProto* result;
}

- (RetrieveUserGamesResponseProto*) defaultInstance;

- (RetrieveUserGamesResponseProto_Builder*) clear;
- (RetrieveUserGamesResponseProto_Builder*) clone;

- (RetrieveUserGamesResponseProto*) build;
- (RetrieveUserGamesResponseProto*) buildPartial;

- (RetrieveUserGamesResponseProto_Builder*) mergeFrom:(RetrieveUserGamesResponseProto*) other;
- (RetrieveUserGamesResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetrieveUserGamesResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (RetrieveUserGamesResponseProto_Builder*) setSender:(BasicUserProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (RetrieveUserGamesResponseProto_Builder*) mergeSender:(BasicUserProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) clearSender;

- (NSArray*) completedGamesList;
- (GameResultsProto*) completedGamesAtIndex:(int32_t) index;
- (RetrieveUserGamesResponseProto_Builder*) replaceCompletedGamesAtIndex:(int32_t) index with:(GameResultsProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addCompletedGames:(GameResultsProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addAllCompletedGames:(NSArray*) values;
- (RetrieveUserGamesResponseProto_Builder*) clearCompletedGamesList;

- (NSArray*) myTurnList;
- (OngoingGameProto*) myTurnAtIndex:(int32_t) index;
- (RetrieveUserGamesResponseProto_Builder*) replaceMyTurnAtIndex:(int32_t) index with:(OngoingGameProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addMyTurn:(OngoingGameProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addAllMyTurn:(NSArray*) values;
- (RetrieveUserGamesResponseProto_Builder*) clearMyTurnList;

- (NSArray*) notMyTurnList;
- (OngoingGameProto*) notMyTurnAtIndex:(int32_t) index;
- (RetrieveUserGamesResponseProto_Builder*) replaceNotMyTurnAtIndex:(int32_t) index with:(OngoingGameProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addNotMyTurn:(OngoingGameProto*) value;
- (RetrieveUserGamesResponseProto_Builder*) addAllNotMyTurn:(NSArray*) values;
- (RetrieveUserGamesResponseProto_Builder*) clearNotMyTurnList;

- (NSArray*) pictureNamesList;
- (NSString*) pictureNamesAtIndex:(int32_t) index;
- (RetrieveUserGamesResponseProto_Builder*) replacePictureNamesAtIndex:(int32_t) index with:(NSString*) value;
- (RetrieveUserGamesResponseProto_Builder*) addPictureNames:(NSString*) value;
- (RetrieveUserGamesResponseProto_Builder*) addAllPictureNames:(NSArray*) values;
- (RetrieveUserGamesResponseProto_Builder*) clearPictureNamesList;

- (BOOL) hasStatus;
- (RetrieveUserGamesResponseProto_RetrieveUserGamesStatus) status;
- (RetrieveUserGamesResponseProto_Builder*) setStatus:(RetrieveUserGamesResponseProto_RetrieveUserGamesStatus) value;
- (RetrieveUserGamesResponseProto_Builder*) clearStatus;
@end

