// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "TriviaQuestionFormat.pb.h"
#import "TriviaRoundFormat.pb.h"
#import "User.pb.h"

@class BasicAuthorizedDeviceProto;
@class BasicAuthorizedDeviceProto_Builder;
@class BasicRoundResultsProto;
@class BasicRoundResultsProto_Builder;
@class BasicUserProto;
@class BasicUserProto_Builder;
@class CompleteRoundResultsProto;
@class CompleteRoundResultsProto_Builder;
@class CompleteUserProto;
@class CompleteUserProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionAnsweredProto;
@class QuestionAnsweredProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
@class SaveRoundProgressRequestProto;
@class SaveRoundProgressRequestProto_Builder;
@class SaveRoundProgressResponseProto;
@class SaveRoundProgressResponseProto_Builder;
@class UnfinishedRoundProto;
@class UnfinishedRoundProto_Builder;
@class UserCurrencyProto;
@class UserCurrencyProto_Builder;
typedef enum {
  SaveRoundProgressResponseProto_SaveRoundStatusSuccess = 1,
  SaveRoundProgressResponseProto_SaveRoundStatusFailOther = 2,
} SaveRoundProgressResponseProto_SaveRoundStatus;

BOOL SaveRoundProgressResponseProto_SaveRoundStatusIsValidValue(SaveRoundProgressResponseProto_SaveRoundStatus value);


@interface SaveRoundProgressEventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SaveRoundProgressRequestProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasSender_:1;
  BOOL hasRound_:1;
  NSString* gameId;
  BasicUserProto* sender;
  UnfinishedRoundProto* round;
}
- (BOOL) hasSender;
- (BOOL) hasGameId;
- (BOOL) hasRound;
@property (readonly, retain) BasicUserProto* sender;
@property (readonly, retain) NSString* gameId;
@property (readonly, retain) UnfinishedRoundProto* round;

+ (SaveRoundProgressRequestProto*) defaultInstance;
- (SaveRoundProgressRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SaveRoundProgressRequestProto_Builder*) builder;
+ (SaveRoundProgressRequestProto_Builder*) builder;
+ (SaveRoundProgressRequestProto_Builder*) builderWithPrototype:(SaveRoundProgressRequestProto*) prototype;

+ (SaveRoundProgressRequestProto*) parseFromData:(NSData*) data;
+ (SaveRoundProgressRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaveRoundProgressRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (SaveRoundProgressRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaveRoundProgressRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SaveRoundProgressRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SaveRoundProgressRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  SaveRoundProgressRequestProto* result;
}

- (SaveRoundProgressRequestProto*) defaultInstance;

- (SaveRoundProgressRequestProto_Builder*) clear;
- (SaveRoundProgressRequestProto_Builder*) clone;

- (SaveRoundProgressRequestProto*) build;
- (SaveRoundProgressRequestProto*) buildPartial;

- (SaveRoundProgressRequestProto_Builder*) mergeFrom:(SaveRoundProgressRequestProto*) other;
- (SaveRoundProgressRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SaveRoundProgressRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (BasicUserProto*) sender;
- (SaveRoundProgressRequestProto_Builder*) setSender:(BasicUserProto*) value;
- (SaveRoundProgressRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue;
- (SaveRoundProgressRequestProto_Builder*) mergeSender:(BasicUserProto*) value;
- (SaveRoundProgressRequestProto_Builder*) clearSender;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (SaveRoundProgressRequestProto_Builder*) setGameId:(NSString*) value;
- (SaveRoundProgressRequestProto_Builder*) clearGameId;

- (BOOL) hasRound;
- (UnfinishedRoundProto*) round;
- (SaveRoundProgressRequestProto_Builder*) setRound:(UnfinishedRoundProto*) value;
- (SaveRoundProgressRequestProto_Builder*) setRoundBuilder:(UnfinishedRoundProto_Builder*) builderForValue;
- (SaveRoundProgressRequestProto_Builder*) mergeRound:(UnfinishedRoundProto*) value;
- (SaveRoundProgressRequestProto_Builder*) clearRound;
@end

@interface SaveRoundProgressResponseProto : PBGeneratedMessage {
@private
  BOOL hasGameId_:1;
  BOOL hasRecipient_:1;
  BOOL hasStatus_:1;
  NSString* gameId;
  BasicUserProto* recipient;
  SaveRoundProgressResponseProto_SaveRoundStatus status;
}
- (BOOL) hasRecipient;
- (BOOL) hasGameId;
- (BOOL) hasStatus;
@property (readonly, retain) BasicUserProto* recipient;
@property (readonly, retain) NSString* gameId;
@property (readonly) SaveRoundProgressResponseProto_SaveRoundStatus status;

+ (SaveRoundProgressResponseProto*) defaultInstance;
- (SaveRoundProgressResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SaveRoundProgressResponseProto_Builder*) builder;
+ (SaveRoundProgressResponseProto_Builder*) builder;
+ (SaveRoundProgressResponseProto_Builder*) builderWithPrototype:(SaveRoundProgressResponseProto*) prototype;

+ (SaveRoundProgressResponseProto*) parseFromData:(NSData*) data;
+ (SaveRoundProgressResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaveRoundProgressResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (SaveRoundProgressResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SaveRoundProgressResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SaveRoundProgressResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SaveRoundProgressResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  SaveRoundProgressResponseProto* result;
}

- (SaveRoundProgressResponseProto*) defaultInstance;

- (SaveRoundProgressResponseProto_Builder*) clear;
- (SaveRoundProgressResponseProto_Builder*) clone;

- (SaveRoundProgressResponseProto*) build;
- (SaveRoundProgressResponseProto*) buildPartial;

- (SaveRoundProgressResponseProto_Builder*) mergeFrom:(SaveRoundProgressResponseProto*) other;
- (SaveRoundProgressResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SaveRoundProgressResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRecipient;
- (BasicUserProto*) recipient;
- (SaveRoundProgressResponseProto_Builder*) setRecipient:(BasicUserProto*) value;
- (SaveRoundProgressResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue;
- (SaveRoundProgressResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value;
- (SaveRoundProgressResponseProto_Builder*) clearRecipient;

- (BOOL) hasGameId;
- (NSString*) gameId;
- (SaveRoundProgressResponseProto_Builder*) setGameId:(NSString*) value;
- (SaveRoundProgressResponseProto_Builder*) clearGameId;

- (BOOL) hasStatus;
- (SaveRoundProgressResponseProto_SaveRoundStatus) status;
- (SaveRoundProgressResponseProto_Builder*) setStatus:(SaveRoundProgressResponseProto_SaveRoundStatus) value;
- (SaveRoundProgressResponseProto_Builder*) clearStatus;
@end

