// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "SearchForUserEvent.pb.h"

@implementation SearchForUserEventRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [SearchForUserEventRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UserRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface SearchForUserRequestProto ()
@property (retain) BasicUserProto* sender;
@property (retain) NSString* nameOfPerson;
@end

@implementation SearchForUserRequestProto

- (BOOL) hasSender {
  return !!hasSender_;
}
- (void) setHasSender:(BOOL) value {
  hasSender_ = !!value;
}
@synthesize sender;
- (BOOL) hasNameOfPerson {
  return !!hasNameOfPerson_;
}
- (void) setHasNameOfPerson:(BOOL) value {
  hasNameOfPerson_ = !!value;
}
@synthesize nameOfPerson;
- (void) dealloc {
  self.sender = nil;
  self.nameOfPerson = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sender = [BasicUserProto defaultInstance];
    self.nameOfPerson = @"";
  }
  return self;
}
static SearchForUserRequestProto* defaultSearchForUserRequestProtoInstance = nil;
+ (void) initialize {
  if (self == [SearchForUserRequestProto class]) {
    defaultSearchForUserRequestProtoInstance = [[SearchForUserRequestProto alloc] init];
  }
}
+ (SearchForUserRequestProto*) defaultInstance {
  return defaultSearchForUserRequestProtoInstance;
}
- (SearchForUserRequestProto*) defaultInstance {
  return defaultSearchForUserRequestProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSender) {
    [output writeMessage:1 value:self.sender];
  }
  if (self.hasNameOfPerson) {
    [output writeString:2 value:self.nameOfPerson];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasSender) {
    size += computeMessageSize(1, self.sender);
  }
  if (self.hasNameOfPerson) {
    size += computeStringSize(2, self.nameOfPerson);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (SearchForUserRequestProto*) parseFromData:(NSData*) data {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromData:data] build];
}
+ (SearchForUserRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserRequestProto*) parseFromInputStream:(NSInputStream*) input {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromInputStream:input] build];
}
+ (SearchForUserRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromCodedInputStream:input] build];
}
+ (SearchForUserRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserRequestProto*)[[[SearchForUserRequestProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserRequestProto_Builder*) builder {
  return [[[SearchForUserRequestProto_Builder alloc] init] autorelease];
}
+ (SearchForUserRequestProto_Builder*) builderWithPrototype:(SearchForUserRequestProto*) prototype {
  return [[SearchForUserRequestProto builder] mergeFrom:prototype];
}
- (SearchForUserRequestProto_Builder*) builder {
  return [SearchForUserRequestProto builder];
}
@end

@interface SearchForUserRequestProto_Builder()
@property (retain) SearchForUserRequestProto* result;
@end

@implementation SearchForUserRequestProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[SearchForUserRequestProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SearchForUserRequestProto_Builder*) clear {
  self.result = [[[SearchForUserRequestProto alloc] init] autorelease];
  return self;
}
- (SearchForUserRequestProto_Builder*) clone {
  return [SearchForUserRequestProto builderWithPrototype:result];
}
- (SearchForUserRequestProto*) defaultInstance {
  return [SearchForUserRequestProto defaultInstance];
}
- (SearchForUserRequestProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SearchForUserRequestProto*) buildPartial {
  SearchForUserRequestProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (SearchForUserRequestProto_Builder*) mergeFrom:(SearchForUserRequestProto*) other {
  if (other == [SearchForUserRequestProto defaultInstance]) {
    return self;
  }
  if (other.hasSender) {
    [self mergeSender:other.sender];
  }
  if (other.hasNameOfPerson) {
    [self setNameOfPerson:other.nameOfPerson];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SearchForUserRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SearchForUserRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        BasicUserProto_Builder* subBuilder = [BasicUserProto builder];
        if (self.hasSender) {
          [subBuilder mergeFrom:self.sender];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSender:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setNameOfPerson:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSender {
  return result.hasSender;
}
- (BasicUserProto*) sender {
  return result.sender;
}
- (SearchForUserRequestProto_Builder*) setSender:(BasicUserProto*) value {
  result.hasSender = YES;
  result.sender = value;
  return self;
}
- (SearchForUserRequestProto_Builder*) setSenderBuilder:(BasicUserProto_Builder*) builderForValue {
  return [self setSender:[builderForValue build]];
}
- (SearchForUserRequestProto_Builder*) mergeSender:(BasicUserProto*) value {
  if (result.hasSender &&
      result.sender != [BasicUserProto defaultInstance]) {
    result.sender =
      [[[BasicUserProto builderWithPrototype:result.sender] mergeFrom:value] buildPartial];
  } else {
    result.sender = value;
  }
  result.hasSender = YES;
  return self;
}
- (SearchForUserRequestProto_Builder*) clearSender {
  result.hasSender = NO;
  result.sender = [BasicUserProto defaultInstance];
  return self;
}
- (BOOL) hasNameOfPerson {
  return result.hasNameOfPerson;
}
- (NSString*) nameOfPerson {
  return result.nameOfPerson;
}
- (SearchForUserRequestProto_Builder*) setNameOfPerson:(NSString*) value {
  result.hasNameOfPerson = YES;
  result.nameOfPerson = value;
  return self;
}
- (SearchForUserRequestProto_Builder*) clearNameOfPerson {
  result.hasNameOfPerson = NO;
  result.nameOfPerson = @"";
  return self;
}
@end

@interface SearchForUserResponseProto ()
@property (retain) BasicUserProto* recipient;
@property (retain) NSString* nameOfPersonId;
@property SearchForUserResponseProto_SearchForUserStatus status;
@end

@implementation SearchForUserResponseProto

- (BOOL) hasRecipient {
  return !!hasRecipient_;
}
- (void) setHasRecipient:(BOOL) value {
  hasRecipient_ = !!value;
}
@synthesize recipient;
- (BOOL) hasNameOfPersonId {
  return !!hasNameOfPersonId_;
}
- (void) setHasNameOfPersonId:(BOOL) value {
  hasNameOfPersonId_ = !!value;
}
@synthesize nameOfPersonId;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (void) dealloc {
  self.recipient = nil;
  self.nameOfPersonId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.recipient = [BasicUserProto defaultInstance];
    self.nameOfPersonId = @"";
    self.status = SearchForUserResponseProto_SearchForUserStatusSuccess;
  }
  return self;
}
static SearchForUserResponseProto* defaultSearchForUserResponseProtoInstance = nil;
+ (void) initialize {
  if (self == [SearchForUserResponseProto class]) {
    defaultSearchForUserResponseProtoInstance = [[SearchForUserResponseProto alloc] init];
  }
}
+ (SearchForUserResponseProto*) defaultInstance {
  return defaultSearchForUserResponseProtoInstance;
}
- (SearchForUserResponseProto*) defaultInstance {
  return defaultSearchForUserResponseProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRecipient) {
    [output writeMessage:1 value:self.recipient];
  }
  if (self.hasNameOfPersonId) {
    [output writeString:2 value:self.nameOfPersonId];
  }
  if (self.hasStatus) {
    [output writeEnum:3 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasRecipient) {
    size += computeMessageSize(1, self.recipient);
  }
  if (self.hasNameOfPersonId) {
    size += computeStringSize(2, self.nameOfPersonId);
  }
  if (self.hasStatus) {
    size += computeEnumSize(3, self.status);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (SearchForUserResponseProto*) parseFromData:(NSData*) data {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromData:data] build];
}
+ (SearchForUserResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserResponseProto*) parseFromInputStream:(NSInputStream*) input {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromInputStream:input] build];
}
+ (SearchForUserResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromCodedInputStream:input] build];
}
+ (SearchForUserResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchForUserResponseProto*)[[[SearchForUserResponseProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchForUserResponseProto_Builder*) builder {
  return [[[SearchForUserResponseProto_Builder alloc] init] autorelease];
}
+ (SearchForUserResponseProto_Builder*) builderWithPrototype:(SearchForUserResponseProto*) prototype {
  return [[SearchForUserResponseProto builder] mergeFrom:prototype];
}
- (SearchForUserResponseProto_Builder*) builder {
  return [SearchForUserResponseProto builder];
}
@end

BOOL SearchForUserResponseProto_SearchForUserStatusIsValidValue(SearchForUserResponseProto_SearchForUserStatus value) {
  switch (value) {
    case SearchForUserResponseProto_SearchForUserStatusSuccess:
    case SearchForUserResponseProto_SearchForUserStatusFailPersonNotFound:
    case SearchForUserResponseProto_SearchForUserStatusFailOther:
      return YES;
    default:
      return NO;
  }
}
@interface SearchForUserResponseProto_Builder()
@property (retain) SearchForUserResponseProto* result;
@end

@implementation SearchForUserResponseProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[SearchForUserResponseProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SearchForUserResponseProto_Builder*) clear {
  self.result = [[[SearchForUserResponseProto alloc] init] autorelease];
  return self;
}
- (SearchForUserResponseProto_Builder*) clone {
  return [SearchForUserResponseProto builderWithPrototype:result];
}
- (SearchForUserResponseProto*) defaultInstance {
  return [SearchForUserResponseProto defaultInstance];
}
- (SearchForUserResponseProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SearchForUserResponseProto*) buildPartial {
  SearchForUserResponseProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (SearchForUserResponseProto_Builder*) mergeFrom:(SearchForUserResponseProto*) other {
  if (other == [SearchForUserResponseProto defaultInstance]) {
    return self;
  }
  if (other.hasRecipient) {
    [self mergeRecipient:other.recipient];
  }
  if (other.hasNameOfPersonId) {
    [self setNameOfPersonId:other.nameOfPersonId];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SearchForUserResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SearchForUserResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        BasicUserProto_Builder* subBuilder = [BasicUserProto builder];
        if (self.hasRecipient) {
          [subBuilder mergeFrom:self.recipient];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setRecipient:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setNameOfPersonId:[input readString]];
        break;
      }
      case 24: {
        int32_t value = [input readEnum];
        if (SearchForUserResponseProto_SearchForUserStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:3 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasRecipient {
  return result.hasRecipient;
}
- (BasicUserProto*) recipient {
  return result.recipient;
}
- (SearchForUserResponseProto_Builder*) setRecipient:(BasicUserProto*) value {
  result.hasRecipient = YES;
  result.recipient = value;
  return self;
}
- (SearchForUserResponseProto_Builder*) setRecipientBuilder:(BasicUserProto_Builder*) builderForValue {
  return [self setRecipient:[builderForValue build]];
}
- (SearchForUserResponseProto_Builder*) mergeRecipient:(BasicUserProto*) value {
  if (result.hasRecipient &&
      result.recipient != [BasicUserProto defaultInstance]) {
    result.recipient =
      [[[BasicUserProto builderWithPrototype:result.recipient] mergeFrom:value] buildPartial];
  } else {
    result.recipient = value;
  }
  result.hasRecipient = YES;
  return self;
}
- (SearchForUserResponseProto_Builder*) clearRecipient {
  result.hasRecipient = NO;
  result.recipient = [BasicUserProto defaultInstance];
  return self;
}
- (BOOL) hasNameOfPersonId {
  return result.hasNameOfPersonId;
}
- (NSString*) nameOfPersonId {
  return result.nameOfPersonId;
}
- (SearchForUserResponseProto_Builder*) setNameOfPersonId:(NSString*) value {
  result.hasNameOfPersonId = YES;
  result.nameOfPersonId = value;
  return self;
}
- (SearchForUserResponseProto_Builder*) clearNameOfPersonId {
  result.hasNameOfPersonId = NO;
  result.nameOfPersonId = @"";
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (SearchForUserResponseProto_SearchForUserStatus) status {
  return result.status;
}
- (SearchForUserResponseProto_Builder*) setStatus:(SearchForUserResponseProto_SearchForUserStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (SearchForUserResponseProto_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = SearchForUserResponseProto_SearchForUserStatusSuccess;
  return self;
}
@end

