// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "TriviaQuestionFormat.pb.h"

@class BasicRoundResultsProto;
@class BasicRoundResultsProto_Builder;
@class CompleteRoundResultsProto;
@class CompleteRoundResultsProto_Builder;
@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionAnsweredProto;
@class QuestionAnsweredProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
@class UnfinishedRoundProto;
@class UnfinishedRoundProto_Builder;

@interface TriviaRoundFormatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BasicRoundResultsProto : PBGeneratedMessage {
@private
  BOOL hasRoundNumber_:1;
  BOOL hasId_:1;
  BOOL hasScore_:1;
  int32_t roundNumber;
  NSString* id;
  int32_t score;
}
- (BOOL) hasId;
- (BOOL) hasScore;
- (BOOL) hasRoundNumber;
@property (readonly, retain) NSString* id;
@property (readonly) int32_t score;
@property (readonly) int32_t roundNumber;

+ (BasicRoundResultsProto*) defaultInstance;
- (BasicRoundResultsProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasicRoundResultsProto_Builder*) builder;
+ (BasicRoundResultsProto_Builder*) builder;
+ (BasicRoundResultsProto_Builder*) builderWithPrototype:(BasicRoundResultsProto*) prototype;

+ (BasicRoundResultsProto*) parseFromData:(NSData*) data;
+ (BasicRoundResultsProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasicRoundResultsProto*) parseFromInputStream:(NSInputStream*) input;
+ (BasicRoundResultsProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasicRoundResultsProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasicRoundResultsProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasicRoundResultsProto_Builder : PBGeneratedMessage_Builder {
@private
  BasicRoundResultsProto* result;
}

- (BasicRoundResultsProto*) defaultInstance;

- (BasicRoundResultsProto_Builder*) clear;
- (BasicRoundResultsProto_Builder*) clone;

- (BasicRoundResultsProto*) build;
- (BasicRoundResultsProto*) buildPartial;

- (BasicRoundResultsProto_Builder*) mergeFrom:(BasicRoundResultsProto*) other;
- (BasicRoundResultsProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasicRoundResultsProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (BasicRoundResultsProto_Builder*) setId:(NSString*) value;
- (BasicRoundResultsProto_Builder*) clearId;

- (BOOL) hasScore;
- (int32_t) score;
- (BasicRoundResultsProto_Builder*) setScore:(int32_t) value;
- (BasicRoundResultsProto_Builder*) clearScore;

- (BOOL) hasRoundNumber;
- (int32_t) roundNumber;
- (BasicRoundResultsProto_Builder*) setRoundNumber:(int32_t) value;
- (BasicRoundResultsProto_Builder*) clearRoundNumber;
@end

@interface CompleteRoundResultsProto : PBGeneratedMessage {
@private
  BOOL hasStartTime_:1;
  BOOL hasEndTime_:1;
  BOOL hasRoundNumber_:1;
  BOOL hasId_:1;
  BOOL hasScore_:1;
  int64_t startTime;
  int64_t endTime;
  int32_t roundNumber;
  NSString* id;
  int32_t score;
  NSMutableArray* mutableAnswersList;
}
- (BOOL) hasId;
- (BOOL) hasScore;
- (BOOL) hasRoundNumber;
- (BOOL) hasStartTime;
- (BOOL) hasEndTime;
@property (readonly, retain) NSString* id;
@property (readonly) int32_t score;
@property (readonly) int32_t roundNumber;
@property (readonly) int64_t startTime;
@property (readonly) int64_t endTime;
- (NSArray*) answersList;
- (QuestionAnsweredProto*) answersAtIndex:(int32_t) index;

+ (CompleteRoundResultsProto*) defaultInstance;
- (CompleteRoundResultsProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CompleteRoundResultsProto_Builder*) builder;
+ (CompleteRoundResultsProto_Builder*) builder;
+ (CompleteRoundResultsProto_Builder*) builderWithPrototype:(CompleteRoundResultsProto*) prototype;

+ (CompleteRoundResultsProto*) parseFromData:(NSData*) data;
+ (CompleteRoundResultsProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompleteRoundResultsProto*) parseFromInputStream:(NSInputStream*) input;
+ (CompleteRoundResultsProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CompleteRoundResultsProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CompleteRoundResultsProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CompleteRoundResultsProto_Builder : PBGeneratedMessage_Builder {
@private
  CompleteRoundResultsProto* result;
}

- (CompleteRoundResultsProto*) defaultInstance;

- (CompleteRoundResultsProto_Builder*) clear;
- (CompleteRoundResultsProto_Builder*) clone;

- (CompleteRoundResultsProto*) build;
- (CompleteRoundResultsProto*) buildPartial;

- (CompleteRoundResultsProto_Builder*) mergeFrom:(CompleteRoundResultsProto*) other;
- (CompleteRoundResultsProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CompleteRoundResultsProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (CompleteRoundResultsProto_Builder*) setId:(NSString*) value;
- (CompleteRoundResultsProto_Builder*) clearId;

- (BOOL) hasScore;
- (int32_t) score;
- (CompleteRoundResultsProto_Builder*) setScore:(int32_t) value;
- (CompleteRoundResultsProto_Builder*) clearScore;

- (BOOL) hasRoundNumber;
- (int32_t) roundNumber;
- (CompleteRoundResultsProto_Builder*) setRoundNumber:(int32_t) value;
- (CompleteRoundResultsProto_Builder*) clearRoundNumber;

- (NSArray*) answersList;
- (QuestionAnsweredProto*) answersAtIndex:(int32_t) index;
- (CompleteRoundResultsProto_Builder*) replaceAnswersAtIndex:(int32_t) index with:(QuestionAnsweredProto*) value;
- (CompleteRoundResultsProto_Builder*) addAnswers:(QuestionAnsweredProto*) value;
- (CompleteRoundResultsProto_Builder*) addAllAnswers:(NSArray*) values;
- (CompleteRoundResultsProto_Builder*) clearAnswersList;

- (BOOL) hasStartTime;
- (int64_t) startTime;
- (CompleteRoundResultsProto_Builder*) setStartTime:(int64_t) value;
- (CompleteRoundResultsProto_Builder*) clearStartTime;

- (BOOL) hasEndTime;
- (int64_t) endTime;
- (CompleteRoundResultsProto_Builder*) setEndTime:(int64_t) value;
- (CompleteRoundResultsProto_Builder*) clearEndTime;
@end

@interface UnfinishedRoundProto : PBGeneratedMessage {
@private
  BOOL hasRoundNumber_:1;
  BOOL hasSecondsRemaning_:1;
  BOOL hasCurrentQuestionNumber_:1;
  BOOL hasCurrentScore_:1;
  BOOL hasId_:1;
  int32_t roundNumber;
  int32_t secondsRemaning;
  int32_t currentQuestionNumber;
  int32_t currentScore;
  NSString* id;
  NSMutableArray* mutableQuestionsList;
}
- (BOOL) hasId;
- (BOOL) hasRoundNumber;
- (BOOL) hasSecondsRemaning;
- (BOOL) hasCurrentQuestionNumber;
- (BOOL) hasCurrentScore;
@property (readonly, retain) NSString* id;
@property (readonly) int32_t roundNumber;
@property (readonly) int32_t secondsRemaning;
@property (readonly) int32_t currentQuestionNumber;
@property (readonly) int32_t currentScore;
- (NSArray*) questionsList;
- (QuestionProto*) questionsAtIndex:(int32_t) index;

+ (UnfinishedRoundProto*) defaultInstance;
- (UnfinishedRoundProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UnfinishedRoundProto_Builder*) builder;
+ (UnfinishedRoundProto_Builder*) builder;
+ (UnfinishedRoundProto_Builder*) builderWithPrototype:(UnfinishedRoundProto*) prototype;

+ (UnfinishedRoundProto*) parseFromData:(NSData*) data;
+ (UnfinishedRoundProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnfinishedRoundProto*) parseFromInputStream:(NSInputStream*) input;
+ (UnfinishedRoundProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnfinishedRoundProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UnfinishedRoundProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UnfinishedRoundProto_Builder : PBGeneratedMessage_Builder {
@private
  UnfinishedRoundProto* result;
}

- (UnfinishedRoundProto*) defaultInstance;

- (UnfinishedRoundProto_Builder*) clear;
- (UnfinishedRoundProto_Builder*) clone;

- (UnfinishedRoundProto*) build;
- (UnfinishedRoundProto*) buildPartial;

- (UnfinishedRoundProto_Builder*) mergeFrom:(UnfinishedRoundProto*) other;
- (UnfinishedRoundProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UnfinishedRoundProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (UnfinishedRoundProto_Builder*) setId:(NSString*) value;
- (UnfinishedRoundProto_Builder*) clearId;

- (NSArray*) questionsList;
- (QuestionProto*) questionsAtIndex:(int32_t) index;
- (UnfinishedRoundProto_Builder*) replaceQuestionsAtIndex:(int32_t) index with:(QuestionProto*) value;
- (UnfinishedRoundProto_Builder*) addQuestions:(QuestionProto*) value;
- (UnfinishedRoundProto_Builder*) addAllQuestions:(NSArray*) values;
- (UnfinishedRoundProto_Builder*) clearQuestionsList;

- (BOOL) hasRoundNumber;
- (int32_t) roundNumber;
- (UnfinishedRoundProto_Builder*) setRoundNumber:(int32_t) value;
- (UnfinishedRoundProto_Builder*) clearRoundNumber;

- (BOOL) hasSecondsRemaning;
- (int32_t) secondsRemaning;
- (UnfinishedRoundProto_Builder*) setSecondsRemaning:(int32_t) value;
- (UnfinishedRoundProto_Builder*) clearSecondsRemaning;

- (BOOL) hasCurrentQuestionNumber;
- (int32_t) currentQuestionNumber;
- (UnfinishedRoundProto_Builder*) setCurrentQuestionNumber:(int32_t) value;
- (UnfinishedRoundProto_Builder*) clearCurrentQuestionNumber;

- (BOOL) hasCurrentScore;
- (int32_t) currentScore;
- (UnfinishedRoundProto_Builder*) setCurrentScore:(int32_t) value;
- (UnfinishedRoundProto_Builder*) clearCurrentScore;
@end

