// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MultipleChoiceAnswerProto;
@class MultipleChoiceAnswerProto_Builder;
@class MultipleChoiceQuestionProto;
@class MultipleChoiceQuestionProto_Builder;
@class PictureQuestionProto;
@class PictureQuestionProto_Builder;
@class QuestionProto;
@class QuestionProto_Builder;
typedef enum {
  MultipleChoiceAnswerProto_AnswerTypeText = 1,
  MultipleChoiceAnswerProto_AnswerTypePicture = 2,
} MultipleChoiceAnswerProto_AnswerType;

BOOL MultipleChoiceAnswerProto_AnswerTypeIsValidValue(MultipleChoiceAnswerProto_AnswerType value);


@interface TriviaQuestionFormatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface QuestionProto : PBGeneratedMessage {
@private
  BOOL hasMultipleChoice_:1;
  BOOL hasPictures_:1;
  MultipleChoiceQuestionProto* multipleChoice;
  PictureQuestionProto* pictures;
}
- (BOOL) hasMultipleChoice;
- (BOOL) hasPictures;
@property (readonly, retain) MultipleChoiceQuestionProto* multipleChoice;
@property (readonly, retain) PictureQuestionProto* pictures;

+ (QuestionProto*) defaultInstance;
- (QuestionProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QuestionProto_Builder*) builder;
+ (QuestionProto_Builder*) builder;
+ (QuestionProto_Builder*) builderWithPrototype:(QuestionProto*) prototype;

+ (QuestionProto*) parseFromData:(NSData*) data;
+ (QuestionProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuestionProto*) parseFromInputStream:(NSInputStream*) input;
+ (QuestionProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QuestionProto_Builder : PBGeneratedMessage_Builder {
@private
  QuestionProto* result;
}

- (QuestionProto*) defaultInstance;

- (QuestionProto_Builder*) clear;
- (QuestionProto_Builder*) clone;

- (QuestionProto*) build;
- (QuestionProto*) buildPartial;

- (QuestionProto_Builder*) mergeFrom:(QuestionProto*) other;
- (QuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMultipleChoice;
- (MultipleChoiceQuestionProto*) multipleChoice;
- (QuestionProto_Builder*) setMultipleChoice:(MultipleChoiceQuestionProto*) value;
- (QuestionProto_Builder*) setMultipleChoiceBuilder:(MultipleChoiceQuestionProto_Builder*) builderForValue;
- (QuestionProto_Builder*) mergeMultipleChoice:(MultipleChoiceQuestionProto*) value;
- (QuestionProto_Builder*) clearMultipleChoice;

- (BOOL) hasPictures;
- (PictureQuestionProto*) pictures;
- (QuestionProto_Builder*) setPictures:(PictureQuestionProto*) value;
- (QuestionProto_Builder*) setPicturesBuilder:(PictureQuestionProto_Builder*) builderForValue;
- (QuestionProto_Builder*) mergePictures:(PictureQuestionProto*) value;
- (QuestionProto_Builder*) clearPictures;
@end

@interface MultipleChoiceQuestionProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasQuestion_:1;
  BOOL hasAnswerId_:1;
  NSString* id;
  NSString* question;
  NSString* answerId;
  NSMutableArray* mutableAnswersList;
}
- (BOOL) hasId;
- (BOOL) hasQuestion;
- (BOOL) hasAnswerId;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* question;
@property (readonly, retain) NSString* answerId;
- (NSArray*) answersList;
- (MultipleChoiceAnswerProto*) answersAtIndex:(int32_t) index;

+ (MultipleChoiceQuestionProto*) defaultInstance;
- (MultipleChoiceQuestionProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MultipleChoiceQuestionProto_Builder*) builder;
+ (MultipleChoiceQuestionProto_Builder*) builder;
+ (MultipleChoiceQuestionProto_Builder*) builderWithPrototype:(MultipleChoiceQuestionProto*) prototype;

+ (MultipleChoiceQuestionProto*) parseFromData:(NSData*) data;
+ (MultipleChoiceQuestionProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MultipleChoiceQuestionProto*) parseFromInputStream:(NSInputStream*) input;
+ (MultipleChoiceQuestionProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MultipleChoiceQuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MultipleChoiceQuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MultipleChoiceQuestionProto_Builder : PBGeneratedMessage_Builder {
@private
  MultipleChoiceQuestionProto* result;
}

- (MultipleChoiceQuestionProto*) defaultInstance;

- (MultipleChoiceQuestionProto_Builder*) clear;
- (MultipleChoiceQuestionProto_Builder*) clone;

- (MultipleChoiceQuestionProto*) build;
- (MultipleChoiceQuestionProto*) buildPartial;

- (MultipleChoiceQuestionProto_Builder*) mergeFrom:(MultipleChoiceQuestionProto*) other;
- (MultipleChoiceQuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MultipleChoiceQuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MultipleChoiceQuestionProto_Builder*) setId:(NSString*) value;
- (MultipleChoiceQuestionProto_Builder*) clearId;

- (BOOL) hasQuestion;
- (NSString*) question;
- (MultipleChoiceQuestionProto_Builder*) setQuestion:(NSString*) value;
- (MultipleChoiceQuestionProto_Builder*) clearQuestion;

- (BOOL) hasAnswerId;
- (NSString*) answerId;
- (MultipleChoiceQuestionProto_Builder*) setAnswerId:(NSString*) value;
- (MultipleChoiceQuestionProto_Builder*) clearAnswerId;

- (NSArray*) answersList;
- (MultipleChoiceAnswerProto*) answersAtIndex:(int32_t) index;
- (MultipleChoiceQuestionProto_Builder*) replaceAnswersAtIndex:(int32_t) index with:(MultipleChoiceAnswerProto*) value;
- (MultipleChoiceQuestionProto_Builder*) addAnswers:(MultipleChoiceAnswerProto*) value;
- (MultipleChoiceQuestionProto_Builder*) addAllAnswers:(NSArray*) values;
- (MultipleChoiceQuestionProto_Builder*) clearAnswersList;
@end

@interface MultipleChoiceAnswerProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasAnswer_:1;
  BOOL hasType_:1;
  NSString* id;
  NSString* answer;
  MultipleChoiceAnswerProto_AnswerType type;
}
- (BOOL) hasId;
- (BOOL) hasAnswer;
- (BOOL) hasType;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* answer;
@property (readonly) MultipleChoiceAnswerProto_AnswerType type;

+ (MultipleChoiceAnswerProto*) defaultInstance;
- (MultipleChoiceAnswerProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MultipleChoiceAnswerProto_Builder*) builder;
+ (MultipleChoiceAnswerProto_Builder*) builder;
+ (MultipleChoiceAnswerProto_Builder*) builderWithPrototype:(MultipleChoiceAnswerProto*) prototype;

+ (MultipleChoiceAnswerProto*) parseFromData:(NSData*) data;
+ (MultipleChoiceAnswerProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MultipleChoiceAnswerProto*) parseFromInputStream:(NSInputStream*) input;
+ (MultipleChoiceAnswerProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MultipleChoiceAnswerProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MultipleChoiceAnswerProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MultipleChoiceAnswerProto_Builder : PBGeneratedMessage_Builder {
@private
  MultipleChoiceAnswerProto* result;
}

- (MultipleChoiceAnswerProto*) defaultInstance;

- (MultipleChoiceAnswerProto_Builder*) clear;
- (MultipleChoiceAnswerProto_Builder*) clone;

- (MultipleChoiceAnswerProto*) build;
- (MultipleChoiceAnswerProto*) buildPartial;

- (MultipleChoiceAnswerProto_Builder*) mergeFrom:(MultipleChoiceAnswerProto*) other;
- (MultipleChoiceAnswerProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MultipleChoiceAnswerProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MultipleChoiceAnswerProto_Builder*) setId:(NSString*) value;
- (MultipleChoiceAnswerProto_Builder*) clearId;

- (BOOL) hasAnswer;
- (NSString*) answer;
- (MultipleChoiceAnswerProto_Builder*) setAnswer:(NSString*) value;
- (MultipleChoiceAnswerProto_Builder*) clearAnswer;

- (BOOL) hasType;
- (MultipleChoiceAnswerProto_AnswerType) type;
- (MultipleChoiceAnswerProto_Builder*) setType:(MultipleChoiceAnswerProto_AnswerType) value;
- (MultipleChoiceAnswerProto_Builder*) clearType;
@end

@interface PictureQuestionProto : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasAnswer_:1;
  NSString* id;
  NSString* answer;
  NSMutableArray* mutableImageNamesList;
}
- (BOOL) hasId;
- (BOOL) hasAnswer;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* answer;
- (NSArray*) imageNamesList;
- (NSString*) imageNamesAtIndex:(int32_t) index;

+ (PictureQuestionProto*) defaultInstance;
- (PictureQuestionProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PictureQuestionProto_Builder*) builder;
+ (PictureQuestionProto_Builder*) builder;
+ (PictureQuestionProto_Builder*) builderWithPrototype:(PictureQuestionProto*) prototype;

+ (PictureQuestionProto*) parseFromData:(NSData*) data;
+ (PictureQuestionProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PictureQuestionProto*) parseFromInputStream:(NSInputStream*) input;
+ (PictureQuestionProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PictureQuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PictureQuestionProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PictureQuestionProto_Builder : PBGeneratedMessage_Builder {
@private
  PictureQuestionProto* result;
}

- (PictureQuestionProto*) defaultInstance;

- (PictureQuestionProto_Builder*) clear;
- (PictureQuestionProto_Builder*) clone;

- (PictureQuestionProto*) build;
- (PictureQuestionProto*) buildPartial;

- (PictureQuestionProto_Builder*) mergeFrom:(PictureQuestionProto*) other;
- (PictureQuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PictureQuestionProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (PictureQuestionProto_Builder*) setId:(NSString*) value;
- (PictureQuestionProto_Builder*) clearId;

- (NSArray*) imageNamesList;
- (NSString*) imageNamesAtIndex:(int32_t) index;
- (PictureQuestionProto_Builder*) replaceImageNamesAtIndex:(int32_t) index with:(NSString*) value;
- (PictureQuestionProto_Builder*) addImageNames:(NSString*) value;
- (PictureQuestionProto_Builder*) addAllImageNames:(NSArray*) values;
- (PictureQuestionProto_Builder*) clearImageNamesList;

- (BOOL) hasAnswer;
- (NSString*) answer;
- (PictureQuestionProto_Builder*) setAnswer:(NSString*) value;
- (PictureQuestionProto_Builder*) clearAnswer;
@end

