// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "User.pb.h"

@implementation UserRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UserRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface BasicUserProto ()
@property (retain) NSString* userId;
@property (retain) NSString* nameStrangersSee;
@property (retain) NSString* nameFriendsSee;
@property (retain) NSString* email;
@property (retain) NSString* password;
@property (retain) NSString* facebookId;
@property (retain) BasicAuthorizedDeviceProto* badp;
@end

@implementation BasicUserProto

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasNameStrangersSee {
  return !!hasNameStrangersSee_;
}
- (void) setHasNameStrangersSee:(BOOL) value {
  hasNameStrangersSee_ = !!value;
}
@synthesize nameStrangersSee;
- (BOOL) hasNameFriendsSee {
  return !!hasNameFriendsSee_;
}
- (void) setHasNameFriendsSee:(BOOL) value {
  hasNameFriendsSee_ = !!value;
}
@synthesize nameFriendsSee;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasFacebookId {
  return !!hasFacebookId_;
}
- (void) setHasFacebookId:(BOOL) value {
  hasFacebookId_ = !!value;
}
@synthesize facebookId;
- (BOOL) hasBadp {
  return !!hasBadp_;
}
- (void) setHasBadp:(BOOL) value {
  hasBadp_ = !!value;
}
@synthesize badp;
- (void) dealloc {
  self.userId = nil;
  self.nameStrangersSee = nil;
  self.nameFriendsSee = nil;
  self.email = nil;
  self.password = nil;
  self.facebookId = nil;
  self.badp = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = @"";
    self.nameStrangersSee = @"";
    self.nameFriendsSee = @"";
    self.email = @"";
    self.password = @"";
    self.facebookId = @"";
    self.badp = [BasicAuthorizedDeviceProto defaultInstance];
  }
  return self;
}
static BasicUserProto* defaultBasicUserProtoInstance = nil;
+ (void) initialize {
  if (self == [BasicUserProto class]) {
    defaultBasicUserProtoInstance = [[BasicUserProto alloc] init];
  }
}
+ (BasicUserProto*) defaultInstance {
  return defaultBasicUserProtoInstance;
}
- (BasicUserProto*) defaultInstance {
  return defaultBasicUserProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeString:1 value:self.userId];
  }
  if (self.hasNameStrangersSee) {
    [output writeString:2 value:self.nameStrangersSee];
  }
  if (self.hasNameFriendsSee) {
    [output writeString:3 value:self.nameFriendsSee];
  }
  if (self.hasEmail) {
    [output writeString:4 value:self.email];
  }
  if (self.hasPassword) {
    [output writeString:5 value:self.password];
  }
  if (self.hasFacebookId) {
    [output writeString:6 value:self.facebookId];
  }
  if (self.hasBadp) {
    [output writeMessage:7 value:self.badp];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeStringSize(1, self.userId);
  }
  if (self.hasNameStrangersSee) {
    size += computeStringSize(2, self.nameStrangersSee);
  }
  if (self.hasNameFriendsSee) {
    size += computeStringSize(3, self.nameFriendsSee);
  }
  if (self.hasEmail) {
    size += computeStringSize(4, self.email);
  }
  if (self.hasPassword) {
    size += computeStringSize(5, self.password);
  }
  if (self.hasFacebookId) {
    size += computeStringSize(6, self.facebookId);
  }
  if (self.hasBadp) {
    size += computeMessageSize(7, self.badp);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (BasicUserProto*) parseFromData:(NSData*) data {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromData:data] build];
}
+ (BasicUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BasicUserProto*) parseFromInputStream:(NSInputStream*) input {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromInputStream:input] build];
}
+ (BasicUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromCodedInputStream:input] build];
}
+ (BasicUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicUserProto*)[[[BasicUserProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicUserProto_Builder*) builder {
  return [[[BasicUserProto_Builder alloc] init] autorelease];
}
+ (BasicUserProto_Builder*) builderWithPrototype:(BasicUserProto*) prototype {
  return [[BasicUserProto builder] mergeFrom:prototype];
}
- (BasicUserProto_Builder*) builder {
  return [BasicUserProto builder];
}
@end

@interface BasicUserProto_Builder()
@property (retain) BasicUserProto* result;
@end

@implementation BasicUserProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[BasicUserProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (BasicUserProto_Builder*) clear {
  self.result = [[[BasicUserProto alloc] init] autorelease];
  return self;
}
- (BasicUserProto_Builder*) clone {
  return [BasicUserProto builderWithPrototype:result];
}
- (BasicUserProto*) defaultInstance {
  return [BasicUserProto defaultInstance];
}
- (BasicUserProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BasicUserProto*) buildPartial {
  BasicUserProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (BasicUserProto_Builder*) mergeFrom:(BasicUserProto*) other {
  if (other == [BasicUserProto defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasNameStrangersSee) {
    [self setNameStrangersSee:other.nameStrangersSee];
  }
  if (other.hasNameFriendsSee) {
    [self setNameFriendsSee:other.nameFriendsSee];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasFacebookId) {
    [self setFacebookId:other.facebookId];
  }
  if (other.hasBadp) {
    [self mergeBadp:other.badp];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BasicUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BasicUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUserId:[input readString]];
        break;
      }
      case 18: {
        [self setNameStrangersSee:[input readString]];
        break;
      }
      case 26: {
        [self setNameFriendsSee:[input readString]];
        break;
      }
      case 34: {
        [self setEmail:[input readString]];
        break;
      }
      case 42: {
        [self setPassword:[input readString]];
        break;
      }
      case 50: {
        [self setFacebookId:[input readString]];
        break;
      }
      case 58: {
        BasicAuthorizedDeviceProto_Builder* subBuilder = [BasicAuthorizedDeviceProto builder];
        if (self.hasBadp) {
          [subBuilder mergeFrom:self.badp];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setBadp:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (NSString*) userId {
  return result.userId;
}
- (BasicUserProto_Builder*) setUserId:(NSString*) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (BasicUserProto_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = @"";
  return self;
}
- (BOOL) hasNameStrangersSee {
  return result.hasNameStrangersSee;
}
- (NSString*) nameStrangersSee {
  return result.nameStrangersSee;
}
- (BasicUserProto_Builder*) setNameStrangersSee:(NSString*) value {
  result.hasNameStrangersSee = YES;
  result.nameStrangersSee = value;
  return self;
}
- (BasicUserProto_Builder*) clearNameStrangersSee {
  result.hasNameStrangersSee = NO;
  result.nameStrangersSee = @"";
  return self;
}
- (BOOL) hasNameFriendsSee {
  return result.hasNameFriendsSee;
}
- (NSString*) nameFriendsSee {
  return result.nameFriendsSee;
}
- (BasicUserProto_Builder*) setNameFriendsSee:(NSString*) value {
  result.hasNameFriendsSee = YES;
  result.nameFriendsSee = value;
  return self;
}
- (BasicUserProto_Builder*) clearNameFriendsSee {
  result.hasNameFriendsSee = NO;
  result.nameFriendsSee = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (BasicUserProto_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (BasicUserProto_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (BasicUserProto_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (BasicUserProto_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasFacebookId {
  return result.hasFacebookId;
}
- (NSString*) facebookId {
  return result.facebookId;
}
- (BasicUserProto_Builder*) setFacebookId:(NSString*) value {
  result.hasFacebookId = YES;
  result.facebookId = value;
  return self;
}
- (BasicUserProto_Builder*) clearFacebookId {
  result.hasFacebookId = NO;
  result.facebookId = @"";
  return self;
}
- (BOOL) hasBadp {
  return result.hasBadp;
}
- (BasicAuthorizedDeviceProto*) badp {
  return result.badp;
}
- (BasicUserProto_Builder*) setBadp:(BasicAuthorizedDeviceProto*) value {
  result.hasBadp = YES;
  result.badp = value;
  return self;
}
- (BasicUserProto_Builder*) setBadpBuilder:(BasicAuthorizedDeviceProto_Builder*) builderForValue {
  return [self setBadp:[builderForValue build]];
}
- (BasicUserProto_Builder*) mergeBadp:(BasicAuthorizedDeviceProto*) value {
  if (result.hasBadp &&
      result.badp != [BasicAuthorizedDeviceProto defaultInstance]) {
    result.badp =
      [[[BasicAuthorizedDeviceProto builderWithPrototype:result.badp] mergeFrom:value] buildPartial];
  } else {
    result.badp = value;
  }
  result.hasBadp = YES;
  return self;
}
- (BasicUserProto_Builder*) clearBadp {
  result.hasBadp = NO;
  result.badp = [BasicAuthorizedDeviceProto defaultInstance];
  return self;
}
@end

@interface BasicAuthorizedDeviceProto ()
@property (retain) NSString* basicAuthorizedDeviceId;
@property (retain) NSString* userId;
@property (retain) NSString* loginToken;
@property int64_t expirationDate;
@property (retain) NSString* udid;
@property (retain) NSString* deviceId;
@end

@implementation BasicAuthorizedDeviceProto

- (BOOL) hasBasicAuthorizedDeviceId {
  return !!hasBasicAuthorizedDeviceId_;
}
- (void) setHasBasicAuthorizedDeviceId:(BOOL) value {
  hasBasicAuthorizedDeviceId_ = !!value;
}
@synthesize basicAuthorizedDeviceId;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasLoginToken {
  return !!hasLoginToken_;
}
- (void) setHasLoginToken:(BOOL) value {
  hasLoginToken_ = !!value;
}
@synthesize loginToken;
- (BOOL) hasExpirationDate {
  return !!hasExpirationDate_;
}
- (void) setHasExpirationDate:(BOOL) value {
  hasExpirationDate_ = !!value;
}
@synthesize expirationDate;
- (BOOL) hasUdid {
  return !!hasUdid_;
}
- (void) setHasUdid:(BOOL) value {
  hasUdid_ = !!value;
}
@synthesize udid;
- (BOOL) hasDeviceId {
  return !!hasDeviceId_;
}
- (void) setHasDeviceId:(BOOL) value {
  hasDeviceId_ = !!value;
}
@synthesize deviceId;
- (void) dealloc {
  self.basicAuthorizedDeviceId = nil;
  self.userId = nil;
  self.loginToken = nil;
  self.udid = nil;
  self.deviceId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.basicAuthorizedDeviceId = @"";
    self.userId = @"";
    self.loginToken = @"";
    self.expirationDate = 0L;
    self.udid = @"";
    self.deviceId = @"";
  }
  return self;
}
static BasicAuthorizedDeviceProto* defaultBasicAuthorizedDeviceProtoInstance = nil;
+ (void) initialize {
  if (self == [BasicAuthorizedDeviceProto class]) {
    defaultBasicAuthorizedDeviceProtoInstance = [[BasicAuthorizedDeviceProto alloc] init];
  }
}
+ (BasicAuthorizedDeviceProto*) defaultInstance {
  return defaultBasicAuthorizedDeviceProtoInstance;
}
- (BasicAuthorizedDeviceProto*) defaultInstance {
  return defaultBasicAuthorizedDeviceProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeString:1 value:self.userId];
  }
  if (self.hasLoginToken) {
    [output writeString:2 value:self.loginToken];
  }
  if (self.hasExpirationDate) {
    [output writeInt64:3 value:self.expirationDate];
  }
  if (self.hasUdid) {
    [output writeString:4 value:self.udid];
  }
  if (self.hasBasicAuthorizedDeviceId) {
    [output writeString:5 value:self.basicAuthorizedDeviceId];
  }
  if (self.hasDeviceId) {
    [output writeString:6 value:self.deviceId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeStringSize(1, self.userId);
  }
  if (self.hasLoginToken) {
    size += computeStringSize(2, self.loginToken);
  }
  if (self.hasExpirationDate) {
    size += computeInt64Size(3, self.expirationDate);
  }
  if (self.hasUdid) {
    size += computeStringSize(4, self.udid);
  }
  if (self.hasBasicAuthorizedDeviceId) {
    size += computeStringSize(5, self.basicAuthorizedDeviceId);
  }
  if (self.hasDeviceId) {
    size += computeStringSize(6, self.deviceId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (BasicAuthorizedDeviceProto*) parseFromData:(NSData*) data {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromData:data] build];
}
+ (BasicAuthorizedDeviceProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BasicAuthorizedDeviceProto*) parseFromInputStream:(NSInputStream*) input {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromInputStream:input] build];
}
+ (BasicAuthorizedDeviceProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicAuthorizedDeviceProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromCodedInputStream:input] build];
}
+ (BasicAuthorizedDeviceProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BasicAuthorizedDeviceProto*)[[[BasicAuthorizedDeviceProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BasicAuthorizedDeviceProto_Builder*) builder {
  return [[[BasicAuthorizedDeviceProto_Builder alloc] init] autorelease];
}
+ (BasicAuthorizedDeviceProto_Builder*) builderWithPrototype:(BasicAuthorizedDeviceProto*) prototype {
  return [[BasicAuthorizedDeviceProto builder] mergeFrom:prototype];
}
- (BasicAuthorizedDeviceProto_Builder*) builder {
  return [BasicAuthorizedDeviceProto builder];
}
@end

@interface BasicAuthorizedDeviceProto_Builder()
@property (retain) BasicAuthorizedDeviceProto* result;
@end

@implementation BasicAuthorizedDeviceProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[BasicAuthorizedDeviceProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (BasicAuthorizedDeviceProto_Builder*) clear {
  self.result = [[[BasicAuthorizedDeviceProto alloc] init] autorelease];
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clone {
  return [BasicAuthorizedDeviceProto builderWithPrototype:result];
}
- (BasicAuthorizedDeviceProto*) defaultInstance {
  return [BasicAuthorizedDeviceProto defaultInstance];
}
- (BasicAuthorizedDeviceProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BasicAuthorizedDeviceProto*) buildPartial {
  BasicAuthorizedDeviceProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (BasicAuthorizedDeviceProto_Builder*) mergeFrom:(BasicAuthorizedDeviceProto*) other {
  if (other == [BasicAuthorizedDeviceProto defaultInstance]) {
    return self;
  }
  if (other.hasBasicAuthorizedDeviceId) {
    [self setBasicAuthorizedDeviceId:other.basicAuthorizedDeviceId];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasLoginToken) {
    [self setLoginToken:other.loginToken];
  }
  if (other.hasExpirationDate) {
    [self setExpirationDate:other.expirationDate];
  }
  if (other.hasUdid) {
    [self setUdid:other.udid];
  }
  if (other.hasDeviceId) {
    [self setDeviceId:other.deviceId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BasicAuthorizedDeviceProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUserId:[input readString]];
        break;
      }
      case 18: {
        [self setLoginToken:[input readString]];
        break;
      }
      case 24: {
        [self setExpirationDate:[input readInt64]];
        break;
      }
      case 34: {
        [self setUdid:[input readString]];
        break;
      }
      case 42: {
        [self setBasicAuthorizedDeviceId:[input readString]];
        break;
      }
      case 50: {
        [self setDeviceId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasBasicAuthorizedDeviceId {
  return result.hasBasicAuthorizedDeviceId;
}
- (NSString*) basicAuthorizedDeviceId {
  return result.basicAuthorizedDeviceId;
}
- (BasicAuthorizedDeviceProto_Builder*) setBasicAuthorizedDeviceId:(NSString*) value {
  result.hasBasicAuthorizedDeviceId = YES;
  result.basicAuthorizedDeviceId = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearBasicAuthorizedDeviceId {
  result.hasBasicAuthorizedDeviceId = NO;
  result.basicAuthorizedDeviceId = @"";
  return self;
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (NSString*) userId {
  return result.userId;
}
- (BasicAuthorizedDeviceProto_Builder*) setUserId:(NSString*) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = @"";
  return self;
}
- (BOOL) hasLoginToken {
  return result.hasLoginToken;
}
- (NSString*) loginToken {
  return result.loginToken;
}
- (BasicAuthorizedDeviceProto_Builder*) setLoginToken:(NSString*) value {
  result.hasLoginToken = YES;
  result.loginToken = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearLoginToken {
  result.hasLoginToken = NO;
  result.loginToken = @"";
  return self;
}
- (BOOL) hasExpirationDate {
  return result.hasExpirationDate;
}
- (int64_t) expirationDate {
  return result.expirationDate;
}
- (BasicAuthorizedDeviceProto_Builder*) setExpirationDate:(int64_t) value {
  result.hasExpirationDate = YES;
  result.expirationDate = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearExpirationDate {
  result.hasExpirationDate = NO;
  result.expirationDate = 0L;
  return self;
}
- (BOOL) hasUdid {
  return result.hasUdid;
}
- (NSString*) udid {
  return result.udid;
}
- (BasicAuthorizedDeviceProto_Builder*) setUdid:(NSString*) value {
  result.hasUdid = YES;
  result.udid = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearUdid {
  result.hasUdid = NO;
  result.udid = @"";
  return self;
}
- (BOOL) hasDeviceId {
  return result.hasDeviceId;
}
- (NSString*) deviceId {
  return result.deviceId;
}
- (BasicAuthorizedDeviceProto_Builder*) setDeviceId:(NSString*) value {
  result.hasDeviceId = YES;
  result.deviceId = value;
  return self;
}
- (BasicAuthorizedDeviceProto_Builder*) clearDeviceId {
  result.hasDeviceId = NO;
  result.deviceId = @"";
  return self;
}
@end

@interface UserCurrencyProto ()
@property int32_t numTokens;
@property int64_t lastTokenRefillTime;
@property int32_t numRubies;
@end

@implementation UserCurrencyProto

- (BOOL) hasNumTokens {
  return !!hasNumTokens_;
}
- (void) setHasNumTokens:(BOOL) value {
  hasNumTokens_ = !!value;
}
@synthesize numTokens;
- (BOOL) hasLastTokenRefillTime {
  return !!hasLastTokenRefillTime_;
}
- (void) setHasLastTokenRefillTime:(BOOL) value {
  hasLastTokenRefillTime_ = !!value;
}
@synthesize lastTokenRefillTime;
- (BOOL) hasNumRubies {
  return !!hasNumRubies_;
}
- (void) setHasNumRubies:(BOOL) value {
  hasNumRubies_ = !!value;
}
@synthesize numRubies;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.numTokens = 0;
    self.lastTokenRefillTime = 0L;
    self.numRubies = 0;
  }
  return self;
}
static UserCurrencyProto* defaultUserCurrencyProtoInstance = nil;
+ (void) initialize {
  if (self == [UserCurrencyProto class]) {
    defaultUserCurrencyProtoInstance = [[UserCurrencyProto alloc] init];
  }
}
+ (UserCurrencyProto*) defaultInstance {
  return defaultUserCurrencyProtoInstance;
}
- (UserCurrencyProto*) defaultInstance {
  return defaultUserCurrencyProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNumTokens) {
    [output writeInt32:1 value:self.numTokens];
  }
  if (self.hasLastTokenRefillTime) {
    [output writeInt64:2 value:self.lastTokenRefillTime];
  }
  if (self.hasNumRubies) {
    [output writeInt32:3 value:self.numRubies];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNumTokens) {
    size += computeInt32Size(1, self.numTokens);
  }
  if (self.hasLastTokenRefillTime) {
    size += computeInt64Size(2, self.lastTokenRefillTime);
  }
  if (self.hasNumRubies) {
    size += computeInt32Size(3, self.numRubies);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (UserCurrencyProto*) parseFromData:(NSData*) data {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromData:data] build];
}
+ (UserCurrencyProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserCurrencyProto*) parseFromInputStream:(NSInputStream*) input {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromInputStream:input] build];
}
+ (UserCurrencyProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserCurrencyProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromCodedInputStream:input] build];
}
+ (UserCurrencyProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserCurrencyProto*)[[[UserCurrencyProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserCurrencyProto_Builder*) builder {
  return [[[UserCurrencyProto_Builder alloc] init] autorelease];
}
+ (UserCurrencyProto_Builder*) builderWithPrototype:(UserCurrencyProto*) prototype {
  return [[UserCurrencyProto builder] mergeFrom:prototype];
}
- (UserCurrencyProto_Builder*) builder {
  return [UserCurrencyProto builder];
}
@end

@interface UserCurrencyProto_Builder()
@property (retain) UserCurrencyProto* result;
@end

@implementation UserCurrencyProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UserCurrencyProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UserCurrencyProto_Builder*) clear {
  self.result = [[[UserCurrencyProto alloc] init] autorelease];
  return self;
}
- (UserCurrencyProto_Builder*) clone {
  return [UserCurrencyProto builderWithPrototype:result];
}
- (UserCurrencyProto*) defaultInstance {
  return [UserCurrencyProto defaultInstance];
}
- (UserCurrencyProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserCurrencyProto*) buildPartial {
  UserCurrencyProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UserCurrencyProto_Builder*) mergeFrom:(UserCurrencyProto*) other {
  if (other == [UserCurrencyProto defaultInstance]) {
    return self;
  }
  if (other.hasNumTokens) {
    [self setNumTokens:other.numTokens];
  }
  if (other.hasLastTokenRefillTime) {
    [self setLastTokenRefillTime:other.lastTokenRefillTime];
  }
  if (other.hasNumRubies) {
    [self setNumRubies:other.numRubies];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserCurrencyProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserCurrencyProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setNumTokens:[input readInt32]];
        break;
      }
      case 16: {
        [self setLastTokenRefillTime:[input readInt64]];
        break;
      }
      case 24: {
        [self setNumRubies:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasNumTokens {
  return result.hasNumTokens;
}
- (int32_t) numTokens {
  return result.numTokens;
}
- (UserCurrencyProto_Builder*) setNumTokens:(int32_t) value {
  result.hasNumTokens = YES;
  result.numTokens = value;
  return self;
}
- (UserCurrencyProto_Builder*) clearNumTokens {
  result.hasNumTokens = NO;
  result.numTokens = 0;
  return self;
}
- (BOOL) hasLastTokenRefillTime {
  return result.hasLastTokenRefillTime;
}
- (int64_t) lastTokenRefillTime {
  return result.lastTokenRefillTime;
}
- (UserCurrencyProto_Builder*) setLastTokenRefillTime:(int64_t) value {
  result.hasLastTokenRefillTime = YES;
  result.lastTokenRefillTime = value;
  return self;
}
- (UserCurrencyProto_Builder*) clearLastTokenRefillTime {
  result.hasLastTokenRefillTime = NO;
  result.lastTokenRefillTime = 0L;
  return self;
}
- (BOOL) hasNumRubies {
  return result.hasNumRubies;
}
- (int32_t) numRubies {
  return result.numRubies;
}
- (UserCurrencyProto_Builder*) setNumRubies:(int32_t) value {
  result.hasNumRubies = YES;
  result.numRubies = value;
  return self;
}
- (UserCurrencyProto_Builder*) clearNumRubies {
  result.hasNumRubies = NO;
  result.numRubies = 0;
  return self;
}
@end

@interface CompleteUserProto ()
@property (retain) NSString* userId;
@property (retain) NSString* nameStrangersSee;
@property (retain) NSString* nameFriendsSee;
@property (retain) NSString* email;
@property (retain) NSString* password;
@property (retain) NSString* facebookId;
@property (retain) BasicAuthorizedDeviceProto* badp;
@property int64_t lastLogin;
@property int64_t signupDate;
@property (retain) UserCurrencyProto* currency;
@end

@implementation CompleteUserProto

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasNameStrangersSee {
  return !!hasNameStrangersSee_;
}
- (void) setHasNameStrangersSee:(BOOL) value {
  hasNameStrangersSee_ = !!value;
}
@synthesize nameStrangersSee;
- (BOOL) hasNameFriendsSee {
  return !!hasNameFriendsSee_;
}
- (void) setHasNameFriendsSee:(BOOL) value {
  hasNameFriendsSee_ = !!value;
}
@synthesize nameFriendsSee;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasFacebookId {
  return !!hasFacebookId_;
}
- (void) setHasFacebookId:(BOOL) value {
  hasFacebookId_ = !!value;
}
@synthesize facebookId;
- (BOOL) hasBadp {
  return !!hasBadp_;
}
- (void) setHasBadp:(BOOL) value {
  hasBadp_ = !!value;
}
@synthesize badp;
- (BOOL) hasLastLogin {
  return !!hasLastLogin_;
}
- (void) setHasLastLogin:(BOOL) value {
  hasLastLogin_ = !!value;
}
@synthesize lastLogin;
- (BOOL) hasSignupDate {
  return !!hasSignupDate_;
}
- (void) setHasSignupDate:(BOOL) value {
  hasSignupDate_ = !!value;
}
@synthesize signupDate;
- (BOOL) hasCurrency {
  return !!hasCurrency_;
}
- (void) setHasCurrency:(BOOL) value {
  hasCurrency_ = !!value;
}
@synthesize currency;
- (void) dealloc {
  self.userId = nil;
  self.nameStrangersSee = nil;
  self.nameFriendsSee = nil;
  self.email = nil;
  self.password = nil;
  self.facebookId = nil;
  self.badp = nil;
  self.currency = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = @"";
    self.nameStrangersSee = @"";
    self.nameFriendsSee = @"";
    self.email = @"";
    self.password = @"";
    self.facebookId = @"";
    self.badp = [BasicAuthorizedDeviceProto defaultInstance];
    self.lastLogin = 0L;
    self.signupDate = 0L;
    self.currency = [UserCurrencyProto defaultInstance];
  }
  return self;
}
static CompleteUserProto* defaultCompleteUserProtoInstance = nil;
+ (void) initialize {
  if (self == [CompleteUserProto class]) {
    defaultCompleteUserProtoInstance = [[CompleteUserProto alloc] init];
  }
}
+ (CompleteUserProto*) defaultInstance {
  return defaultCompleteUserProtoInstance;
}
- (CompleteUserProto*) defaultInstance {
  return defaultCompleteUserProtoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeString:1 value:self.userId];
  }
  if (self.hasNameStrangersSee) {
    [output writeString:2 value:self.nameStrangersSee];
  }
  if (self.hasNameFriendsSee) {
    [output writeString:3 value:self.nameFriendsSee];
  }
  if (self.hasEmail) {
    [output writeString:4 value:self.email];
  }
  if (self.hasPassword) {
    [output writeString:5 value:self.password];
  }
  if (self.hasFacebookId) {
    [output writeString:6 value:self.facebookId];
  }
  if (self.hasBadp) {
    [output writeMessage:7 value:self.badp];
  }
  if (self.hasLastLogin) {
    [output writeInt64:8 value:self.lastLogin];
  }
  if (self.hasSignupDate) {
    [output writeInt64:9 value:self.signupDate];
  }
  if (self.hasCurrency) {
    [output writeMessage:10 value:self.currency];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeStringSize(1, self.userId);
  }
  if (self.hasNameStrangersSee) {
    size += computeStringSize(2, self.nameStrangersSee);
  }
  if (self.hasNameFriendsSee) {
    size += computeStringSize(3, self.nameFriendsSee);
  }
  if (self.hasEmail) {
    size += computeStringSize(4, self.email);
  }
  if (self.hasPassword) {
    size += computeStringSize(5, self.password);
  }
  if (self.hasFacebookId) {
    size += computeStringSize(6, self.facebookId);
  }
  if (self.hasBadp) {
    size += computeMessageSize(7, self.badp);
  }
  if (self.hasLastLogin) {
    size += computeInt64Size(8, self.lastLogin);
  }
  if (self.hasSignupDate) {
    size += computeInt64Size(9, self.signupDate);
  }
  if (self.hasCurrency) {
    size += computeMessageSize(10, self.currency);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CompleteUserProto*) parseFromData:(NSData*) data {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromData:data] build];
}
+ (CompleteUserProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CompleteUserProto*) parseFromInputStream:(NSInputStream*) input {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromInputStream:input] build];
}
+ (CompleteUserProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CompleteUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromCodedInputStream:input] build];
}
+ (CompleteUserProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CompleteUserProto*)[[[CompleteUserProto builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CompleteUserProto_Builder*) builder {
  return [[[CompleteUserProto_Builder alloc] init] autorelease];
}
+ (CompleteUserProto_Builder*) builderWithPrototype:(CompleteUserProto*) prototype {
  return [[CompleteUserProto builder] mergeFrom:prototype];
}
- (CompleteUserProto_Builder*) builder {
  return [CompleteUserProto builder];
}
@end

@interface CompleteUserProto_Builder()
@property (retain) CompleteUserProto* result;
@end

@implementation CompleteUserProto_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CompleteUserProto alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CompleteUserProto_Builder*) clear {
  self.result = [[[CompleteUserProto alloc] init] autorelease];
  return self;
}
- (CompleteUserProto_Builder*) clone {
  return [CompleteUserProto builderWithPrototype:result];
}
- (CompleteUserProto*) defaultInstance {
  return [CompleteUserProto defaultInstance];
}
- (CompleteUserProto*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CompleteUserProto*) buildPartial {
  CompleteUserProto* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CompleteUserProto_Builder*) mergeFrom:(CompleteUserProto*) other {
  if (other == [CompleteUserProto defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasNameStrangersSee) {
    [self setNameStrangersSee:other.nameStrangersSee];
  }
  if (other.hasNameFriendsSee) {
    [self setNameFriendsSee:other.nameFriendsSee];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasFacebookId) {
    [self setFacebookId:other.facebookId];
  }
  if (other.hasBadp) {
    [self mergeBadp:other.badp];
  }
  if (other.hasLastLogin) {
    [self setLastLogin:other.lastLogin];
  }
  if (other.hasSignupDate) {
    [self setSignupDate:other.signupDate];
  }
  if (other.hasCurrency) {
    [self mergeCurrency:other.currency];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CompleteUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CompleteUserProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUserId:[input readString]];
        break;
      }
      case 18: {
        [self setNameStrangersSee:[input readString]];
        break;
      }
      case 26: {
        [self setNameFriendsSee:[input readString]];
        break;
      }
      case 34: {
        [self setEmail:[input readString]];
        break;
      }
      case 42: {
        [self setPassword:[input readString]];
        break;
      }
      case 50: {
        [self setFacebookId:[input readString]];
        break;
      }
      case 58: {
        BasicAuthorizedDeviceProto_Builder* subBuilder = [BasicAuthorizedDeviceProto builder];
        if (self.hasBadp) {
          [subBuilder mergeFrom:self.badp];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setBadp:[subBuilder buildPartial]];
        break;
      }
      case 64: {
        [self setLastLogin:[input readInt64]];
        break;
      }
      case 72: {
        [self setSignupDate:[input readInt64]];
        break;
      }
      case 82: {
        UserCurrencyProto_Builder* subBuilder = [UserCurrencyProto builder];
        if (self.hasCurrency) {
          [subBuilder mergeFrom:self.currency];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setCurrency:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (NSString*) userId {
  return result.userId;
}
- (CompleteUserProto_Builder*) setUserId:(NSString*) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (CompleteUserProto_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = @"";
  return self;
}
- (BOOL) hasNameStrangersSee {
  return result.hasNameStrangersSee;
}
- (NSString*) nameStrangersSee {
  return result.nameStrangersSee;
}
- (CompleteUserProto_Builder*) setNameStrangersSee:(NSString*) value {
  result.hasNameStrangersSee = YES;
  result.nameStrangersSee = value;
  return self;
}
- (CompleteUserProto_Builder*) clearNameStrangersSee {
  result.hasNameStrangersSee = NO;
  result.nameStrangersSee = @"";
  return self;
}
- (BOOL) hasNameFriendsSee {
  return result.hasNameFriendsSee;
}
- (NSString*) nameFriendsSee {
  return result.nameFriendsSee;
}
- (CompleteUserProto_Builder*) setNameFriendsSee:(NSString*) value {
  result.hasNameFriendsSee = YES;
  result.nameFriendsSee = value;
  return self;
}
- (CompleteUserProto_Builder*) clearNameFriendsSee {
  result.hasNameFriendsSee = NO;
  result.nameFriendsSee = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (CompleteUserProto_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (CompleteUserProto_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (CompleteUserProto_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (CompleteUserProto_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasFacebookId {
  return result.hasFacebookId;
}
- (NSString*) facebookId {
  return result.facebookId;
}
- (CompleteUserProto_Builder*) setFacebookId:(NSString*) value {
  result.hasFacebookId = YES;
  result.facebookId = value;
  return self;
}
- (CompleteUserProto_Builder*) clearFacebookId {
  result.hasFacebookId = NO;
  result.facebookId = @"";
  return self;
}
- (BOOL) hasBadp {
  return result.hasBadp;
}
- (BasicAuthorizedDeviceProto*) badp {
  return result.badp;
}
- (CompleteUserProto_Builder*) setBadp:(BasicAuthorizedDeviceProto*) value {
  result.hasBadp = YES;
  result.badp = value;
  return self;
}
- (CompleteUserProto_Builder*) setBadpBuilder:(BasicAuthorizedDeviceProto_Builder*) builderForValue {
  return [self setBadp:[builderForValue build]];
}
- (CompleteUserProto_Builder*) mergeBadp:(BasicAuthorizedDeviceProto*) value {
  if (result.hasBadp &&
      result.badp != [BasicAuthorizedDeviceProto defaultInstance]) {
    result.badp =
      [[[BasicAuthorizedDeviceProto builderWithPrototype:result.badp] mergeFrom:value] buildPartial];
  } else {
    result.badp = value;
  }
  result.hasBadp = YES;
  return self;
}
- (CompleteUserProto_Builder*) clearBadp {
  result.hasBadp = NO;
  result.badp = [BasicAuthorizedDeviceProto defaultInstance];
  return self;
}
- (BOOL) hasLastLogin {
  return result.hasLastLogin;
}
- (int64_t) lastLogin {
  return result.lastLogin;
}
- (CompleteUserProto_Builder*) setLastLogin:(int64_t) value {
  result.hasLastLogin = YES;
  result.lastLogin = value;
  return self;
}
- (CompleteUserProto_Builder*) clearLastLogin {
  result.hasLastLogin = NO;
  result.lastLogin = 0L;
  return self;
}
- (BOOL) hasSignupDate {
  return result.hasSignupDate;
}
- (int64_t) signupDate {
  return result.signupDate;
}
- (CompleteUserProto_Builder*) setSignupDate:(int64_t) value {
  result.hasSignupDate = YES;
  result.signupDate = value;
  return self;
}
- (CompleteUserProto_Builder*) clearSignupDate {
  result.hasSignupDate = NO;
  result.signupDate = 0L;
  return self;
}
- (BOOL) hasCurrency {
  return result.hasCurrency;
}
- (UserCurrencyProto*) currency {
  return result.currency;
}
- (CompleteUserProto_Builder*) setCurrency:(UserCurrencyProto*) value {
  result.hasCurrency = YES;
  result.currency = value;
  return self;
}
- (CompleteUserProto_Builder*) setCurrencyBuilder:(UserCurrencyProto_Builder*) builderForValue {
  return [self setCurrency:[builderForValue build]];
}
- (CompleteUserProto_Builder*) mergeCurrency:(UserCurrencyProto*) value {
  if (result.hasCurrency &&
      result.currency != [UserCurrencyProto defaultInstance]) {
    result.currency =
      [[[UserCurrencyProto builderWithPrototype:result.currency] mergeFrom:value] buildPartial];
  } else {
    result.currency = value;
  }
  result.hasCurrency = YES;
  return self;
}
- (CompleteUserProto_Builder*) clearCurrency {
  result.hasCurrency = NO;
  result.currency = [UserCurrencyProto defaultInstance];
  return self;
}
@end

